// dbMarket.js
const dbMarket = {
"1. HCMC_Chợ Bà Lát": { di: "Bình Chánh", ec: 5 },
"1. HCMC_Chợ Bình Chánh": { di: "Bình Chánh", ec: 10 },
"1. HCMC_Chợ Cầu Xáng": { di: "Bình Chánh", ec: 5 },
"1. HCMC_Chợ Đệm": { di: "Bình Chánh", ec: 5 },
"1. HCMC_Chợ Hưng Long": { di: "Bình Chánh", ec: 5 },
"1. HCMC_Chợ Lê Minh Xuân": { di: "Bình Chánh", ec: 5 },
"1. HCMC_Chợ Vĩnh Lộc": { di: "Bình Chánh", ec: 15 },
"1. HCMC_Chợ Vĩnh Lộc A": { di: "Bình Chánh", ec: 8 },
"1. HCMC_Chợ Vĩnh Lộc B": { di: "Bình Chánh", ec: 8 },
"1. HCMC_Chợ An Lạc": { di: "Bình Tân", ec: 5 },
"1. HCMC_Chợ Bà Hom": { di: "Bình Tân", ec: 5 },
"1. HCMC_Chợ Bình Hưng Hoà": { di: "Bình Tân", ec: 11 },
"1. HCMC_Chợ Bình Long": { di: "Bình Tân", ec: 9 },
"1. HCMC_Chợ Bình Thành": { di: "Bình Tân", ec: 8 },
"1. HCMC_Chợ Bình Trị Đông": { di: "Bình Tân", ec: 20 },
"1. HCMC_Chợ Đất Mới": { di: "Bình Tân", ec: 5 },
"1. HCMC_Chợ Dĩa Tân Tạo": { di: "Bình Tân", ec: 7 },
"1. HCMC_Chợ Gò Xoài": { di: "Bình Tân", ec: 8 },
"1. HCMC_Chợ Kênh 19/5": { di: "Bình Tân", ec: 4 },
"1. HCMC_Chợ Khu Phố 2": { di: "Bình Tân", ec: 5 },
"1. HCMC_Chợ Kiến Đức": { di: "Bình Tân", ec: 5 },
"1. HCMC_Chợ Lê Đình Cẩn": { di: "Bình Tân", ec: 6 },
"1. HCMC_Chợ Ngã Tư Bốn Xã": { di: "Bình Tân", ec: 8 },
"1. HCMC_Chợ Phạm Đăng Giảng": { di: "Bình Tân", ec: 8 },
"1. HCMC_Chợ Bà Chiểu": { di: "Bình Thạnh", ec: 40 },
"1. HCMC_Chợ Cây Quéo": { di: "Bình Thạnh", ec: 12 },
"1. HCMC_Chợ Chiều Võ Duy Ninh": { di: "Bình Thạnh", ec: 7 },
"1. HCMC_Chợ Phan Văn Trị": { di: "Bình Thạnh", ec: 7 },
"1. HCMC_Chợ Phường 25": { di: "Bình Thạnh", ec: 11 },
"1. HCMC_Chợ Tạm Nguyễn Xí": { di: "Bình Thạnh", ec: 5 },
"1. HCMC_Chợ Thanh Đa": { di: "Bình Thạnh", ec: 10 },
"1. HCMC_Chợ Thị Nghè": { di: "Bình Thạnh", ec: 22 },
"1. HCMC_Chợ Vạn Kiếp": { di: "Bình Thạnh", ec: 8 },
"1. HCMC_Chợ Văn Thánh": { di: "Bình Thạnh", ec: 8 },
"1. HCMC_Bình Khánh": { di: "Cần Giờ", ec: 8 },
"1. HCMC_Chợ An Thới Đông": { di: "Cần Giờ", ec: 5 },
"1. HCMC_Chợ Đồng Hòa": { di: "Cần Giờ", ec: 2 },
"1. HCMC_Chợ Hòa Hiệp": { di: "Cần Giờ", ec: 2 },
"1. HCMC_Chợ Lý Nhơn": { di: "Cần Giờ", ec: 2 },
"1. HCMC_Chợ Bình Mỹ": { di: "Củ Chi", ec: 5 },
"1. HCMC_Chợ Củ Chi": { di: "Củ Chi", ec: 10 },
"1. HCMC_Chợ Tân Phú Trung": { di: "Củ Chi", ec: 15 },
"1. HCMC_Chợ Tân Thạnh Đông": { di: "Củ Chi", ec: 5 },
"1. HCMC_Chợ Tân Thông Hội": { di: "Củ Chi", ec: 14 },
"1. HCMC_Chợ Trung An": { di: "Củ Chi", ec: 5 },
"1. HCMC_Phú Hòa Đông": { di: "Củ Chi", ec: 5 },
"1. HCMC_Chợ An Hội": { di: "Gò Vấp", ec: 4 },
"1. HCMC_Chợ An Nhơn": { di: "Gò Vấp", ec: 8 },
"1. HCMC_Chợ Căn Cứ": { di: "Gò Vấp", ec: 15 },
"1. HCMC_Chợ Gò Vấp": { di: "Gò Vấp", ec: 13 },
"1. HCMC_Chợ Hạnh Thông Tây": { di: "Gò Vấp", ec: 5 },
"1. HCMC_Chợ Tân Sơn Nhất": { di: "Gò Vấp", ec: 12 },
"1. HCMC_Chợ Thạch Đà": { di: "Gò Vấp", ec: 10 },
"1. HCMC_Chợ Xóm Mới": { di: "Gò Vấp", ec: 4 },
"1. HCMC_Chợ Bà Điểm": { di: "Hóc Môn", ec: 6 },
"1. HCMC_Chợ Bùi Môn": { di: "Hóc Môn", ec: 4 },
"1. HCMC_Chợ Cây Me": { di: "Hóc Môn", ec: 7 },
"1. HCMC_Chợ Đông Thạnh": { di: "Hóc Môn", ec: 5 },
"1. HCMC_Chợ Hóc Môn": { di: "Hóc Môn", ec: 14 },
"1. HCMC_Chợ Nhị Xuân": { di: "Hóc Môn", ec: 4 },
"1. HCMC_Chợ Tạm Tân Hiệp": { di: "Hóc Môn", ec: 3 },
"1. HCMC_Chợ Tân Thới Nhì": { di: "Hóc Môn", ec: 4 },
"1. HCMC_Chợ Trần Văn Mười": { di: "Hóc Môn", ec: 4 },
"1. HCMC_Chợ Trung Chánh": { di: "Hóc Môn", ec: 12 },
"1. HCMC_Chợ Xuân Thới Thượng": { di: "Hóc Môn", ec: 8 },
"1. HCMC_Chợ Ấp 3": { di: "Nhà Bè", ec: 2 },
"1. HCMC_Chợ Bà Chồi": { di: "Nhà Bè", ec: 5 },
"1. HCMC_Chợ Bờ Băng": { di: "Nhà Bè", ec: 2 },
"1. HCMC_Chợ Cầu Kinh": { di: "Nhà Bè", ec: 3 },
"1. HCMC_Chợ Nhơn Đức": { di: "Nhà Bè", ec: 3 },
"1. HCMC_Chợ Phú Lễ": { di: "Nhà Bè", ec: 5 },
"1. HCMC_Chợ Phú Xuân": { di: "Nhà Bè", ec: 5 },
"1. HCMC_Chợ Phước Lộc": { di: "Nhà Bè", ec: 2 },
"1. HCMC_Chợ Phước Kiểng": { di: "Nhà Bè", ec: 7 },
"1. HCMC_Chợ Cô Giang": { di: "Phú Nhuận", ec: 4 },
"1. HCMC_Chợ Kênh Cây Khô": { di: "Nhà Bè", ec: 5 },
"1. HCMC_Chợ Nguyễn Đình Chiểu": { di: "Phú Nhuận", ec: 24 },
"1. HCMC_Chợ Phú Nhuận": { di: "Phú Nhuận", ec: 28 },
"1. HCMC_Chợ Trần Hữu Trang": { di: "Phú Nhuận", ec: 15 },
"1. HCMC_Chợ Bến Thành": { di: "Quận 1", ec: 8 },
"1. HCMC_Chợ Cầu Kho": { di: "Quận 1", ec: 5 },
"1. HCMC_Chợ Cầu Ông Lãnh": { di: "Quận 1", ec: 5 },
"1. HCMC_Chợ Đakao": { di: "Quận 1", ec: 8 },
"1. HCMC_Chợ Tân Định": { di: "Quận 1", ec: 28 },
"1. HCMC_Chợ Thái Bình": { di: "Quận 1", ec: 25 },
"1. HCMC_Chợ Tôn Thất Đạm": { di: "Quận 1", ec: 12 },
"1. HCMC_Chợ Yersin": { di: "Quận 1", ec: 7 },
"1. HCMC_Chợ Chí Hòa": { di: "Quận 10", ec: 6 },
"1. HCMC_Chợ Da Bà Bầu ": { di: "Quận 10", ec: 7 },
"1. HCMC_Chợ Hồ Thị Kỷ": { di: "Quận 10", ec: 5 },
"1. HCMC_Chợ Hòa Hưng": { di: "Quận 10", ec: 10 },
"1. HCMC_Chợ Lê Hồng Phong": { di: "Quận 10", ec: 8 },
"1. HCMC_Chợ Nguyễn Tri Phương": { di: "Quận 10", ec: 19 },
"1. HCMC_Chợ Nhật Tảo": { di: "Quận 10", ec: 6 },
"1. HCMC_Chợ Phường 10": { di: "Quận 10", ec: 4 },
"1. HCMC_Chợ Phường 2": { di: "Quận 10", ec: 4 },
"1. HCMC_Chợ Bình Thới": { di: "Quận 11", ec: 18 },
"1. HCMC_Chợ Chim Xanh": { di: "Quận 11", ec: 12 },
"1. HCMC_Chợ Hà Tôn Quyền": { di: "Quận 11", ec: 8 },
"1. HCMC_Chợ Lãnh Binh Thăng": { di: "Quận 11", ec: 12 },
"1. HCMC_Chợ Nhỏ Tự Phát": { di: "Quận 11", ec: 3 },
"1. HCMC_Chợ Phú Thọ": { di: "Quận 11", ec: 8 },
"1. HCMC_Chợ Thiếc": { di: "Quận 11", ec: 7 },
"1. HCMC_Chợ An Phú Đông": { di: "Quận 12", ec: 8 },
"1. HCMC_Chợ An Sương": { di: "Quận 12", ec: 16 },
"1. HCMC_Chợ Cầu": { di: "Quận 12", ec: 10 },
"1. HCMC_Chợ Chiều Tô Ký": { di: "Quận 12", ec: 4 },
"1. HCMC_Chợ Đông Quang": { di: "Quận 12", ec: 3 },
"1. HCMC_Chợ Giãn Dân": { di: "Quận 12", ec: 4 },
"1. HCMC_Chợ Hạt Điều": { di: "Quận 12", ec: 4 },
"1. HCMC_Chợ Hiệp Thành": { di: "Quận 12", ec: 8 },
"1. HCMC_Chợ Lạc Quang": { di: "Quận 12", ec: 9 },
"1. HCMC_Chợ Minh Phát": { di: "Quận 12", ec: 5 },
"1. HCMC_Chợ Nam Long": { di: "Quận 12", ec: 5 },
"1. HCMC_Chợ Ngã Ba Bầu": { di: "Quận 12", ec: 5 },
"1. HCMC_Chợ Tạm Cây Sộp": { di: "Quận 12", ec: 4 },
"1. HCMC_Chợ Tạm Thới An": { di: "Quận 12", ec: 5 },
"1. HCMC_Chợ Tạm Vườn Lài": { di: "Quận 12", ec: 6 },
"1. HCMC_Chợ Tân Chánh Hiệp": { di: "Quận 12", ec: 10 },
"1. HCMC_Chợ Thạnh Lộc": { di: "Quận 12", ec: 4 },
"1. HCMC_Chợ Thạnh Xuân": { di: "Quận 12", ec: 9 },
"1. HCMC_Chợ Thới An": { di: "Quận 12", ec: 4 },
"1. HCMC_Chợ Tô Ký": { di: "Quận 12", ec: 2 },
"1. HCMC_Chợ Việt Hưng": { di: "Quận 12", ec: 4 },
"1. HCMC_Chợ Vườn Lài": { di: "Quận 12", ec: 15 },
"1. HCMC_Chợ Bàn Cờ": { di: "Quận 3", ec: 12 },
"1. HCMC_Chợ Bùi Phát": { di: "Quận 3", ec: 4 },
"1. HCMC_Chợ Lê Văn Sỹ": { di: "Quận 3", ec: 7 },
"1. HCMC_Chợ Nguyễn Văn Trỗi": { di: "Quận 3", ec: 18 },
"1. HCMC_Chợ Vườn Chuối": { di: "Quận 3", ec: 6 },
"1. HCMC_Chợ 200": { di: "Quận 4", ec: 5 },
"1. HCMC_Chợ Cầu Cống": { di: "Quận 4", ec: 5 },
"1. HCMC_Chợ Đường Đoàn Văn Bơ": { di: "Quận 4", ec: 13 },
"1. HCMC_Chợ Hãng Dệt": { di: "Quận 4", ec: 3 },
"1. HCMC_Chợ Hãng Phân": { di: "Quận 4", ec: 5 },
"1. HCMC_Chợ Kho 11": { di: "Quận 4", ec: 3 },
"1. HCMC_Chợ Long Kiểng": { di: "Quận 4", ec: 5 },
"1. HCMC_Chợ Nguyễn Khoái": { di: "Quận 4", ec: 5 },
"1. HCMC_Chợ Tôn Thất Thuyết": { di: "Quận 4", ec: 4 },
"1. HCMC_Chợ Xóm Chiếu": { di: "Quận 4", ec: 20 },
"1. HCMC_Chợ An Đông": { di: "Quận 5", ec: 5 },
"1. HCMC_Chợ Bầu Sen": { di: "Quận 5", ec: 4 },
"1. HCMC_Chợ Cao Đạt": { di: "Quận 5", ec: 5 },
"1. HCMC_Chợ Hòa Bình": { di: "Quận 5", ec: 25 },
"1. HCMC_Chợ Phùng Hưng": { di: "Quận 5", ec: 4 },
"1. HCMC_Chợ Thuận Kiều": { di: "Quận 5", ec: 5 },
"1. HCMC_Chợ Thực Phẩm An Đông": { di: "Quận 5", ec: 9 },
"1. HCMC_Chợ Xã Tây": { di: "Quận 5", ec: 5 },
"1. HCMC_Chợ Xóm Vôi": { di: "Quận 5", ec: 6 },
"1. HCMC_Chợ An Dương Vương": { di: "Quận 6", ec: 4 },
"1. HCMC_Chợ Bình Tây": { di: "Quận 6", ec: 45 },
"1. HCMC_Chợ Bình Tiên": { di: "Quận 6", ec: 12 },
"1. HCMC_Chợ Hồ Trọng Quý": { di: "Quận 6", ec: 5 },
"1. HCMC_Chợ Lê Tấn Kế": { di: "Quận 6", ec: 25 },
"1. HCMC_Chợ Lò Gốm": { di: "Quận 6", ec: 4 },
"1. HCMC_Chợ Minh Phụng": { di: "Quận 6", ec: 4 },
"1. HCMC_Chợ Phú Định": { di: "Quận 6", ec: 8 },
"1. HCMC_Chợ Phú Lâm": { di: "Quận 6", ec: 18 },
"1. HCMC_Chợ Tân Hoà Đông": { di: "Quận 6", ec: 3 },
"1. HCMC_Chợ Trần Bình": { di: "Quận 6", ec: 20 },
"1. HCMC_Chợ Cư Xá Ngân Hàng": { di: "Quận 7", ec: 4 },
"1. HCMC_Chợ Gò Ô Môi": { di: "Quận 7", ec: 4 },
"1. HCMC_Chợ Phú Thuận": { di: "Quận 7", ec: 4 },
"1. HCMC_Chợ Phước Long": { di: "Quận 7", ec: 4 },
"1. HCMC_Chợ Rạch Đĩa": { di: "Quận 7", ec: 4 },
"1. HCMC_Chợ Tạm Bùi Văn Ba": { di: "Quận 7", ec: 4 },
"1. HCMC_Chợ Tân Kiểng 1": { di: "Quận 7", ec: 6 },
"1. HCMC_Chợ Tân Kiểng 2": { di: "Quận 7", ec: 6 },
"1. HCMC_Chợ Tân Mỹ ": { di: "Quận 7", ec: 6 },
"1. HCMC_Chợ Tân Quy": { di: "Quận 7", ec: 6 },
"1. HCMC_Chợ Tân Thuận": { di: "Quận 7", ec: 4 },
"1. HCMC_Chợ Tân Thuận Đông": { di: "Quận 7", ec: 4 },
"1. HCMC_Chợ Ba Đình": { di: "Quận 8", ec: 4 },
"1. HCMC_Chợ Bến Bình Đông": { di: "Quận 8", ec: 10 },
"1. HCMC_Chợ Bình An": { di: "Quận 8", ec: 3 },
"1. HCMC_Chợ Bình Điền": { di: "Quận 8", ec: 30 },
"1. HCMC_Chợ Bình Đông": { di: "Quận 8", ec: 4 },
"1. HCMC_Chợ Hưng Phú": { di: "Quận 8", ec: 4 },
"1. HCMC_Chợ Lò Than": { di: "Quận 8", ec: 5 },
"1. HCMC_Chợ Nguyễn Chế Nghĩa": { di: "Quận 8", ec: 4 },
"1. HCMC_Chợ Nhị Thiên Đường": { di: "Quận 8", ec: 8 },
"1. HCMC_Chợ Phạm Thế Hiển": { di: "Quận 8", ec: 10 },
"1. HCMC_Chợ Phú Lợi 2": { di: "Quận 8", ec: 2 },
"1. HCMC_Chợ Rạch Cát": { di: "Quận 8", ec: 4 },
"1. HCMC_Chợ Rạch Ông": { di: "Quận 8", ec: 18 },
"1. HCMC_Chợ Trần Văn Thành": { di: "Quận 8", ec: 4 },
"1. HCMC_Chợ Vạn Nguyên": { di: "Quận 8", ec: 3 },
"1. HCMC_Chợ Xóm Củi": { di: "Quận 8", ec: 12 },
"1. HCMC_Phú Định": { di: "Quận 8", ec: 3 },
"1. HCMC_Chợ Gò Công": { di: "Quận 9", ec: 4 },
"1. HCMC_Chợ Hiệp Phú": { di: "Quận 9", ec: 8 },
"1. HCMC_Chợ Hoa Cau": { di: "Quận 9", ec: 2 },
"1. HCMC_Chợ Kiến Thiết": { di: "Quận 9", ec: 5 },
"1. HCMC_Chợ Long Phước": { di: "Quận 9", ec: 4 },
"1. HCMC_Chợ Long Thạnh Mỹ": { di: "Quận 9", ec: 4 },
"1. HCMC_Chợ Long Trường": { di: "Quận 9", ec: 6 },
"1. HCMC_Chợ Nam Hoà ( Phước Long A)": { di: "Quận 9", ec: 4 },
"1. HCMC_Chợ Phước Bình": { di: "Quận 9", ec: 14 },
"1. HCMC_Chợ Phước Long B": { di: "Quận 9", ec: 4 },
"1. HCMC_Chợ Tăng Nhơn Phú A": { di: "Quận 9", ec: 6 },
"1. HCMC_Chợ Tăng Nhơn Phú B": { di: "Quận 9", ec: 6 },
"1. HCMC_Chợ Tây Hòa": { di: "Quận 9", ec: 2 },
"1. HCMC_Chợ Bà Hoa": { di: "Tân Bình", ec: 11 },
"1. HCMC_Chợ Bảo Ngọc Tú": { di: "Tân Bình", ec: 4 },
"1. HCMC_Chợ Bàu Cát": { di: "Tân Bình", ec: 4 },
"1. HCMC_Chợ Hoàng Hoa Thám": { di: "Tân Bình", ec: 18 },
"1. HCMC_Chợ Nam Hòa": { di: "Tân Bình", ec: 6 },
"1. HCMC_Chợ Nghĩa Phát": { di: "Tân Bình", ec: 6 },
"1. HCMC_Chợ Ông Hoàng": { di: "Tân Bình", ec: 13 },
"1. HCMC_Chợ Phạm Văn Hai": { di: "Tân Bình", ec: 24 },
"1. HCMC_Chợ Tạm Phạm Văn Bạch": { di: "Tân Bình", ec: 7 },
"1. HCMC_Chợ Tân Bình": { di: "Tân Bình", ec: 30 },
"1. HCMC_Chợ Tân Hưng": { di: "Tân Bình", ec: 5 },
"1. HCMC_Chợ Tân Phước": { di: "Tân Bình", ec: 8 },
"1. HCMC_Chợ Tân Trụ": { di: "Tân Bình", ec: 8 },
"1. HCMC_Chợ Trần Văn Quang": { di: "Tân Bình", ec: 6 },
"1. HCMC_Chợ Võ Thành Trang": { di: "Tân Bình", ec: 8 },
"1. HCMC_Chợ Hiệp Tân": { di: "Tân Phú", ec: 9 },
"1. HCMC_Chợ Hoàng Ngọc Phách": { di: "Tân Phú", ec: 8 },
"1. HCMC_Chợ Phú Trung": { di: "Tân Phú", ec: 8 },
"1. HCMC_Chợ Phường 17": { di: "Tân Phú", ec: 18 },
"1. HCMC_Chợ Phường 20": { di: "Tân Phú", ec: 15 },
"1. HCMC_Chợ Sơn Kỳ": { di: "Tân Phú", ec: 11 },
"1. HCMC_Chợ Tạm Huỳnh Văn Chính": { di: "Tân Phú", ec: 5 },
"1. HCMC_Chợ Tạm Thống Nhất": { di: "Tân Phú", ec: 5 },
"1. HCMC_Chợ Tân Hương": { di: "Tân Phú", ec: 5 },
"1. HCMC_Chợ Tân Phú 1": { di: "Tân Phú", ec: 6 },
"1. HCMC_Chợ An Bình": { di: "Thủ Đức", ec: 5 },
"1. HCMC_Chợ Bình Khánh": { di: "Thủ Đức", ec: 7 },
"1. HCMC_Chợ Bình Phước": { di: "Thủ Đức", ec: 8 },
"1. HCMC_Chợ Bình Triệu": { di: "Thủ Đức", ec: 6 },
"1. HCMC_Chợ Bình Trưng": { di: "Thủ Đức", ec: 5 },
"1. HCMC_Chợ Cát Lái": { di: "Thủ Đức", ec: 5 },
"1. HCMC_Chợ Cây Xoài": { di: "Thủ Đức", ec: 7 },
"1. HCMC_Chợ Đo Đạc": { di: "Thủ Đức", ec: 5 },
"1. HCMC_Chợ Hiệp Bình Chánh": { di: "Thủ Đức", ec: 10 },
"1. HCMC_Chợ Linh Trung": { di: "Thủ Đức", ec: 6 },
"1. HCMC_Chợ Linh Xuân": { di: "Thủ Đức", ec: 6 },
"1. HCMC_Chợ Tam Bình": { di: "Thủ Đức", ec: 9 },
"1. HCMC_Chợ Tam Hà": { di: "Thủ Đức", ec: 8 },
"1. HCMC_Chợ Tạm Hiệp Bình Chánh": { di: "Thủ Đức", ec: 5 },
"1. HCMC_Chợ Tân Lập": { di: "Thủ Đức", ec: 8 },
"1. HCMC_Chợ Thạnh Mỹ Lợi": { di: "Thủ Đức", ec: 5 },
"1. HCMC_Chợ Thảo Điền": { di: "Thủ Đức", ec: 5 },
"1. HCMC_Chợ Thủ Đức": { di: "Thủ Đức", ec: 12 },
"1. HCMC_Chợ Thủ Đức B": { di: "Thủ Đức", ec: 14 },
"1. HCMC_Chợ Từ Đức": { di: "Thủ Đức", ec: 6 },
"1. HCMC_Chợ Xuân Hiệp": { di: "Thủ Đức", ec: 5 },
"1. HCMC_Chợ Chó": { di: "Quận 12", ec: 5 },
"1. HCMC_Chợ Tăng Nhơn Phú": { di: "Thủ Đức", ec: 9 },
"1. HCMC_Chợ Việt Kiều": { di: "Hóc Môn", ec: 7 },
"1. HCMC_Chợ Tân Thới Thượng": { di: "Hóc Môn", ec: 7 },
"1. HCMC_Tạp Hóa": { di: "Chưa Rõ", ec: 1 },
"1. HCMC_Chợ 1A": { di: "Thủ Đức", ec: 5 },
"1. HCMC_Chợ Liên Ấp 123": { di: "Bình Chánh", ec: 5 },
"1. HCMC_Chợ Mỹ Nga": { di: "Bình Tân", ec: 7 },
"1. HCMC_Chợ Nhỏ": { di: "Quận 1", ec: 5 },
"1. HCMC_Chợ Nhỏ Hoàng Diệu": { di: "Quận 4", ec: 7 },
"1. HCMC_Chợ Hiệp Bình Phước": { di: "Thủ Đức", ec: 8 },

"1. Ha Noi_Chợ Long Biên": { di: "Ba Đình", ec: 60 },
"1. Ha Noi_Chợ Thành Công B": { di: "Ba Đình", ec: 25 },
"1. Ha Noi_Chợ Châu Long": { di: "Ba Đình", ec: 18 },
"1. Ha Noi_Chợ Cống Vị": { di: "Ba Đình", ec: 20 },
"1. Ha Noi_Chợ Ngọc Hà": { di: "Ba Đình", ec: 12 },
"1. Ha Noi_Chợ Thành Công A": { di: "Ba Đình", ec: 30 },
"1. Ha Noi_Chợ Linh Lang": { di: "Ba Đình", ec: 18 },
"1. Ha Noi_Chợ Hữu Tiệp": { di: "Ba Đình", ec: 8 },
"1. Ha Noi_Chợ Quảng Oai": { di: "Ba Vì", ec: 38 },
"1. Ha Noi_Chợ Ba Trại": { di: "Ba Vì", ec: 12 },
"1. Ha Noi_Chợ Suối Hai": { di: "Ba Vì", ec: 8 },
"1. Ha Noi_Chợ Chu": { di: "Ba Vì", ec: 6 },
"1. Ha Noi_Chợ Kiều Mộc": { di: "Ba Vì", ec: 8 },
"1. Ha Noi_Chợ Chẹ": { di: "Ba Vì", ec: 8 },
"1. Ha Noi_Chợ Mộc": { di: "Ba Vì", ec: 8 },
"1. Ha Noi_Chợ Hàng Vải": { di: "Ba Vì", ec: 8 },
"1. Ha Noi_Chợ Vắp": { di: "Ba Vì", ec: 5 },
"1. Ha Noi_Chợ Phúc": { di: "Ba Vì", ec: 6 },
"1. Ha Noi_Chợ Phú Thịnh ": { di: "Ba Vì", ec: 6 },
"1. Ha Noi_Chợ Phú Phương": { di: "Ba Vì", ec: 6 },
"1. Ha Noi_Chợ Nhông": { di: "Ba Vì", ec: 12 },
"1. Ha Noi_Chợ Dầy": { di: "Ba Vì", ec: 6 },
"1. Ha Noi_Chợ Dốc": { di: "Ba Vì", ec: 8 },
"1. Ha Noi_Chợ Tản Lĩnh ": { di: "Ba Vì", ec: 18 },
"1. Ha Noi_Chợ Thuần Mỹ": { di: "Ba Vì", ec: 6 },
"1. Ha Noi_Chợ Thuỵ An": { di: "Ba Vì", ec: 6 },
"1. Ha Noi_Chợ Tòng Bạt": { di: "Ba Vì", ec: 10 },
"1. Ha Noi_Chợ Tòng Lệnh": { di: "Ba Vì", ec: 5 },
"1. Ha Noi_Chợ Mơ": { di: "Ba Vì", ec: 10 },
"1. Ha Noi_Chợ Chiều": { di: "Ba Vì", ec: 4 },
"1. Ha Noi_Chợ Vật Lại": { di: "Ba Vì", ec: 12 },
"1. Ha Noi_Chợ Trù Ii": { di: "Bắc Từ Liêm", ec: 7 },
"1. Ha Noi_Chợ Viện E": { di: "Bắc Từ Liêm", ec: 10 },
"1. Ha Noi_Chợ Cổ Nhuế": { di: "Bắc Từ Liêm", ec: 30 },
"1. Ha Noi_Chợ Vẽ ": { di: "Bắc Từ Liêm", ec: 18 },
"1. Ha Noi_Chợ Liên Mạc": { di: "Bắc Từ Liêm", ec: 6 },
"1. Ha Noi_Chợ Đầu Mối Minh Khai": { di: "Bắc Từ Liêm", ec: 75 },
"1. Ha Noi_Chợ Phúc Lý": { di: "Bắc Từ Liêm", ec: 6 },
"1. Ha Noi_Chợ Phú Diễn": { di: "Bắc Từ Liêm", ec: 12 },
"1. Ha Noi_Chợ Hoa Tây Tựu": { di: "Bắc Từ Liêm", ec: 5 },
"1. Ha Noi_Chợ Kẻ ": { di: "Bắc Từ Liêm", ec: 8 },
"1. Ha Noi_Chợ Thụy Phương": { di: "Bắc Từ Liêm", ec: 8 },
"1. Ha Noi_Chợ Xuân Đỉnh 2": { di: "Bắc Từ Liêm", ec: 20 },
"1. Ha Noi_Chợ Xuân Đỉnh 1": { di: "Bắc Từ Liêm", ec: 25 },
"1. Ha Noi_Chợ Cầu Diễn": { di: "Bắc Từ Liêm", ec: 35 },
"1. Ha Noi_Chợ Nghĩa Tân": { di: "Cầu Giấy", ec: 40 },
"1. Ha Noi_Chợ Cầu Giấy": { di: "Cầu Giấy", ec: 15 },
"1. Ha Noi_Chợ Quan Hoa": { di: "Cầu Giấy", ec: 12 },
"1. Ha Noi_Chợ Nhà Xanh": { di: "Cầu Giấy", ec: 5 },
"1. Ha Noi_Chợ Ns Dịch Vọng": { di: "Cầu Giấy", ec: 25 },
"1. Ha Noi_Chợ 337 Dịch Vọng": { di: "Cầu Giấy", ec: 8 },
"1. Ha Noi_Chợ Đồng Xa": { di: "Cầu Giấy", ec: 35 },
"1. Ha Noi_Chợ Nghĩa Đô": { di: "Cầu Giấy", ec: 20 },
"1. Ha Noi_Chợ Trung Hòa": { di: "Cầu Giấy", ec: 22 },
"1. Ha Noi_Chợ Hợp Nhất": { di: "Cầu Giấy", ec: 18 },
"1. Ha Noi_Chợ Chúc Sơn": { di: "Chương Mỹ", ec: 40 },
"1. Ha Noi_Chợ Xuân Mai": { di: "Chương Mỹ", ec: 45 },
"1. Ha Noi_Chợ Đông Phương Yên": { di: "Chương Mỹ", ec: 10 },
"1. Ha Noi_Chợ Gốt": { di: "Chương Mỹ", ec: 15 },
"1. Ha Noi_Chợ Trượng": { di: "Chương Mỹ", ec: 10 },
"1. Ha Noi_Chợ Văn Phú": { di: "Chương Mỹ", ec: 5 },
"1. Ha Noi_Chợ Sẽ": { di: "Chương Mỹ", ec: 6 },
"1. Ha Noi_Chợ Gốm": { di: "Chương Mỹ", ec: 8 },
"1. Ha Noi_Chợ Lam Điền": { di: "Chương Mỹ", ec: 6 },
"1. Ha Noi_Chợ Cá": { di: "Chương Mỹ", ec: 6 },
"1. Ha Noi_Chợ Cống": { di: "Chương Mỹ", ec: 6 },
"1. Ha Noi_Chợ Mụ": { di: "Chương Mỹ", ec: 4 },
"1. Ha Noi_Chợ Phú Vinh": { di: "Chương Mỹ", ec: 18 },
"1. Ha Noi_Chợ Phượng": { di: "Chương Mỹ", ec: 12 },
"1. Ha Noi_Chợ Quảng Bị": { di: "Chương Mỹ", ec: 12 },
"1. Ha Noi_Chợ Cời ": { di: "Chương Mỹ", ec: 7 },
"1. Ha Noi_Chợ Rồng": { di: "Chương Mỹ", ec: 5 },
"1. Ha Noi_Chợ Trôi": { di: "Chương Mỹ", ec: 5 },
"1. Ha Noi_Chợ Bê Tông": { di: "Chương Mỹ", ec: 15 },
"1. Ha Noi_Chợ Sở": { di: "Chương Mỹ", ec: 8 },
"1. Ha Noi_Chợ Rét": { di: "Chương Mỹ", ec: 8 },
"1. Ha Noi_Chợ Miếu Môn": { di: "Chương Mỹ", ec: 10 },
"1. Ha Noi_Chợ Giường ": { di: "Chương Mỹ", ec: 5 },
"1. Ha Noi_Chợ Phùng": { di: "Đan Phượng", ec: 35 },
"1. Ha Noi_Chợ Bá": { di: "Đan Phượng", ec: 12 },
"1. Ha Noi_Chợ Dày": { di: "Đan Phượng", ec: 14 },
"1. Ha Noi_Chợ Địch": { di: "Đan Phượng", ec: 8 },
"1. Ha Noi_Chợ Gối": { di: "Đan Phượng", ec: 15 },
"1. Ha Noi_Chợ Đình": { di: "Đan Phượng", ec: 12 },
"1. Ha Noi_Chợ Thọ Xuân": { di: "Đan Phượng", ec: 10 },
"1. Ha Noi_Chợ Kim Nỗ": { di: "Đông Anh", ec: 22 },
"1. Ha Noi_Chợ Tt Đông Anh": { di: "Đông Anh", ec: 45 },
"1. Ha Noi_Chợ Lắp Ghép": { di: "Đông Anh", ec: 20 },
"1. Ha Noi_Chợ Ga": { di: "Đông Anh", ec: 18 },
"1. Ha Noi_Chợ Bắc Hồng": { di: "Đông Anh", ec: 10 },
"1. Ha Noi_Chợ Đông Trù": { di: "Đông Anh", ec: 10 },
"1. Ha Noi_Chợ Dục Tú": { di: "Đông Anh", ec: 7 },
"1. Ha Noi_Chợ Cổ Điển": { di: "Đông Anh", ec: 28 },
"1. Ha Noi_Chợ Bỏi": { di: "Đông Anh", ec: 6 },
"1. Ha Noi_Chợ Liên Hà": { di: "Đông Anh", ec: 25 },
"1. Ha Noi_Chợ Mai Lâm": { di: "Đông Anh", ec: 8 },
"1. Ha Noi_Chợ Nam Hồng": { di: "Đông Anh", ec: 14 },
"1. Ha Noi_Chợ Nhội": { di: "Đông Anh", ec: 8 },
"1. Ha Noi_Chợ Tó": { di: "Đông Anh", ec: 38 },
"1. Ha Noi_Chợ Kính Nỗ": { di: "Đông Anh", ec: 15 },
"1. Ha Noi_Chợ Ống": { di: "Đông Anh", ec: 8 },
"1. Ha Noi_Chợ Vân Trì": { di: "Đông Anh", ec: 9 },
"1. Ha Noi_Chợ Rau Vân Nội": { di: "Đông Anh", ec: 15 },
"1. Ha Noi_Chợ Dục Nội": { di: "Đông Anh", ec: 12 },
"1. Ha Noi_Chợ Vĩnh Ngọc ": { di: "Đông Anh", ec: 16 },
"1. Ha Noi_Chợ Kim": { di: "Đông Anh", ec: 12 },
"1. Ha Noi_Chợ H27 Khương Thượng": { di: "Đống Đa", ec: 6 },
"1. Ha Noi_Chợ Láng Thượng": { di: "Đống Đa", ec: 18 },
"1. Ha Noi_Chợ Khâm Thiên": { di: "Đống Đa", ec: 22 },
"1. Ha Noi_Chợ Thổ Quan": { di: "Đống Đa", ec: 10 },
"1. Ha Noi_Chợ A12 Khương Thượng": { di: "Đống Đa", ec: 12 },
"1. Ha Noi_Chợ Ngã Tư Sở": { di: "Đống Đa", ec: 35 },
"1. Ha Noi_Chợ Láng Hạ": { di: "Đống Đa", ec: 20 },
"1. Ha Noi_Chợ Thái Hà": { di: "Đống Đa", ec: 25 },
"1. Ha Noi_Chợ Ngô Sĩ Liên": { di: "Đống Đa", ec: 15 },
"1. Ha Noi_Chợ Cổng Học Viện Nn1": { di: "Gia Lâm", ec: 20 },
"1. Ha Noi_Chợ Sáng": { di: "Gia Lâm", ec: 8 },
"1. Ha Noi_Chợ Giang Cao": { di: "Gia Lâm", ec: 5 },
"1. Ha Noi_Chợ Vàng": { di: "Gia Lâm", ec: 25 },
"1. Ha Noi_Chợ Bún": { di: "Gia Lâm", ec: 15 },
"1. Ha Noi_Chợ Đình Xuyên": { di: "Gia Lâm", ec: 10 },
"1. Ha Noi_Chợ Đông Dư": { di: "Gia Lâm", ec: 7 },
"1. Ha Noi_Chợ Dương Quang": { di: "Gia Lâm", ec: 9 },
"1. Ha Noi_Chợ Yên Mỹ": { di: "Gia Lâm", ec: 5 },
"1. Ha Noi_Chợ Dương Xá": { di: "Gia Lâm", ec: 14 },
"1. Ha Noi_Chợ Cậy": { di: "Gia Lâm", ec: 12 },
"1. Ha Noi_Chợ Kim Lan": { di: "Gia Lâm", ec: 10 },
"1. Ha Noi_Chợ Keo": { di: "Gia Lâm", ec: 12 },
"1. Ha Noi_Chợ Thôn 2": { di: "Gia Lâm", ec: 35 },
"1. Ha Noi_Chợ Thôn 7": { di: "Gia Lâm", ec: 45 },
"1. Ha Noi_Chợ Thôn 9": { di: "Gia Lâm", ec: 40 },
"1. Ha Noi_Chợ Thôn 5": { di: "Gia Lâm", ec: 30 },
"1. Ha Noi_Chợ Gióng": { di: "Gia Lâm", ec: 12 },
"1. Ha Noi_Chợ Sủi": { di: "Gia Lâm", ec: 28 },
"1. Ha Noi_Chợ Trung Màu": { di: "Gia Lâm", ec: 6 },
"1. Ha Noi_Chợ Văn Đức": { di: "Gia Lâm", ec: 8 },
"1. Ha Noi_Trùng Quán": { di: "Gia Lâm", ec: 8 },
"1. Ha Noi_Chợ Yên Thường": { di: "Gia Lâm", ec: 22 },
"1. Ha Noi_Chợ Dốc Lã": { di: "Gia Lâm", ec: 40 },
"1. Ha Noi_Chợ Yên Viên": { di: "Gia Lâm", ec: 8 },
"1. Ha Noi_Chợ Cống Thôn": { di: "Gia Lâm", ec: 6 },
"1. Ha Noi_Chợ Mai Lĩnh": { di: "Hà Đông", ec: 10 },
"1. Ha Noi_Chợ Đồng Mai": { di: "Hà Đông", ec: 8 },
"1. Ha Noi_Chợ La Cả": { di: "Hà Đông", ec: 10 },
"1. Ha Noi_Chợ La Dương": { di: "Hà Đông", ec: 7 },
"1. Ha Noi_Chợ Mậu Lương": { di: "Hà Đông", ec: 10 },
"1. Ha Noi_Chợ Bông Đỏ": { di: "Hà Đông", ec: 12 },
"1. Ha Noi_Chợ Đình La Khê": { di: "Hà Đông", ec: 6 },
"1. Ha Noi_Chợ La Khê": { di: "Hà Đông", ec: 18 },
"1. Ha Noi_Chợ Hà Đông": { di: "Hà Đông", ec: 80 },
"1. Ha Noi_Chợ Văn La": { di: "Hà Đông", ec: 25 },
"1. Ha Noi_Chợ Xốm": { di: "Hà Đông", ec: 25 },
"1. Ha Noi_Chợ Yên Phúc": { di: "Hà Đông", ec: 8 },
"1. Ha Noi_Chợ Vạn Phúc": { di: "Hà Đông", ec: 15 },
"1. Ha Noi_Chợ Đêm Ns Văn Quán": { di: "Hà Đông", ec: 20 },
"1. Ha Noi_Chợ Yên": { di: "Hà Đông", ec: 8 },
"1. Ha Noi_Chợ Đồng Tâm": { di: "Hai Bà Trưng", ec: 22 },
"1. Ha Noi_Chợ Nguyễn Công Trứ": { di: "Hai Bà Trưng", ec: 18 },
"1. Ha Noi_Chợ Quỳnh Mai": { di: "Hai Bà Trưng", ec: 20 },
"1. Ha Noi_Chợ Hôm-Đức Viên": { di: "Hai Bà Trưng", ec: 65 },
"1. Ha Noi_Chợ Bách Khoa": { di: "Hai Bà Trưng", ec: 16 },
"1. Ha Noi_Chợ Vĩnh Tuy": { di: "Hai Bà Trưng", ec: 15 },
"1. Ha Noi_Chợ Giang Xá": { di: "Hoài Đức", ec: 25 },
"1. Ha Noi_Chợ Ngãi Cầu": { di: "Hoài Đức", ec: 8 },
"1. Ha Noi_Chợ Phú An": { di: "Hoài Đức", ec: 12 },
"1. Ha Noi_Chợ Đông Lao": { di: "Hoài Đức", ec: 8 },
"1. Ha Noi_Chợ Lưu Xá": { di: "Hoài Đức", ec: 6 },
"1. Ha Noi_Chợ Nghệ": { di: "Hoài Đức", ec: 7 },
"1. Ha Noi_Chợ Sấu": { di: "Hoài Đức", ec: 35 },
"1. Ha Noi_Chợ La Phù": { di: "Hoài Đức", ec: 25 },
"1. Ha Noi_Chợ Lại Yên": { di: "Hoài Đức", ec: 12 },
"1. Ha Noi_Chợ Sơn Đồng": { di: "Hoài Đức", ec: 18 },
"1. Ha Noi_Chợ Vạng": { di: "Hoài Đức", ec: 8 },
"1. Ha Noi_Chợ Vân Canh": { di: "Hoài Đức", ec: 14 },
"1. Ha Noi_Chợ Lềnh": { di: "Hoài Đức", ec: 6 },
"1. Ha Noi_Chợ Giá": { di: "Hoài Đức", ec: 20 },
"1. Ha Noi_Chợ Điếm 3": { di: "Hoài Đức", ec: 5 },
"1. Ha Noi_Chợ Cầu Đông": { di: "Hoàn Kiếm", ec: 30 },
"1. Ha Noi_Chợ Đồng Xuân": { di: "Hoàn Kiếm", ec: 180 },
"1. Ha Noi_Chợ Hàng Da": { di: "Hoàn Kiếm", ec: 40 },
"1. Ha Noi_Thực Phẩm Tươi Sống Đx- Bắc Qua": { di: "Hoàn Kiếm", ec: 45 },
"1. Ha Noi_Chợ 19/12": { di: "Hoàn Kiếm", ec: 12 },
"1. Ha Noi_Chợ Cửa Nam": { di: "Hoàn Kiếm", ec: 10 },
"1. Ha Noi_Chợ Vĩnh Tuy (Hoàng Mai)": { di: "Hoàng Mai", ec: 15 },
"1. Ha Noi_Chợ Đại Từ": { di: "Hoàng Mai", ec: 32 },
"1. Ha Noi_Chợ Đầu Mối Phía Nam": { di: "Hoàng Mai", ec: 70 },
"1. Ha Noi_Chợ Kim Lũ": { di: "Hoàng Mai", ec: 10 },
"1. Ha Noi_Chợ Xanh Định Công": { di: "Hoàng Mai", ec: 22 },
"1. Ha Noi_Chợ Xanh Linh Đàm": { di: "Hoàng Mai", ec: 25 },
"1. Ha Noi_Chợ Trương Định": { di: "Hoàng Mai", ec: 28 },
"1. Ha Noi_Chợ Hoàng Mai": { di: "Hoàng Mai", ec: 18 },
"1. Ha Noi_Chợ Lòng Thuyền": { di: "Hoàng Mai", ec: 8 },
"1. Ha Noi_Chợ Cầu Nghè": { di: "Hoàng Mai", ec: 6 },
"1. Ha Noi_Chợ Lĩnh Nam": { di: "Hoàng Mai", ec: 20 },
"1. Ha Noi_Chợ Mai Động": { di: "Hoàng Mai", ec: 22 },
"1. Ha Noi_Chợ Thanh Trì": { di: "Hoàng Mai", ec: 8 },
"1. Ha Noi_Chợ Giáp Nhị": { di: "Hoàng Mai", ec: 12 },
"1. Ha Noi_Phường Cự Khối": { di: "Long Biên", ec: 6 },
"1. Ha Noi_Chợ Ô Cách": { di: "Long Biên", ec: 22 },
"1. Ha Noi_Chợ Diêm Gỗ": { di: "Long Biên", ec: 18 },
"1. Ha Noi_Chợ Quán Tình": { di: "Long Biên", ec: 7 },
"1. Ha Noi_Chợ Tình Quang": { di: "Long Biên", ec: 5 },
"1. Ha Noi_Chợ Tư Đình": { di: "Long Biên", ec: 20 },
"1. Ha Noi_Chợ Gia Lâm": { di: "Long Biên", ec: 35 },
"1. Ha Noi_Chợ Tổ 27": { di: "Long Biên", ec: 8 },
"1. Ha Noi_Chợ Ngọc Thuỵ ": { di: "Long Biên", ec: 20 },
"1. Ha Noi_Chợ Tổ 33": { di: "Long Biên", ec: 6 },
"1. Ha Noi_Chợ Tổ 25": { di: "Long Biên", ec: 5 },
"1. Ha Noi_Chợ Tạm Phúc Đồng": { di: "Long Biên", ec: 8 },
"1. Ha Noi_Chợ May 10 Mới": { di: "Long Biên", ec: 25 },
"1. Ha Noi_Chợ Phúc Lợi": { di: "Long Biên", ec: 16 },
"1. Ha Noi_Chợ Vũ Xuân Thiều": { di: "Long Biên", ec: 12 },
"1. Ha Noi_Chợ 230": { di: "Long Biên", ec: 10 },
"1. Ha Noi_Chợ Đồng Dinh": { di: "Long Biên", ec: 7 },
"1. Ha Noi_Chợ Thạch Bàn": { di: "Long Biên", ec: 24 },
"1. Ha Noi_Chợ Thượng Cát": { di: "Long Biên", ec: 8 },
"1. Ha Noi_Chợ Gia Quất": { di: "Long Biên", ec: 8 },
"1. Ha Noi_Chợ Đức Hòa": { di: "Long Biên", ec: 6 },
"1. Ha Noi_Chợ Cửa Đình": { di: "Long Biên", ec: 8 },
"1. Ha Noi_Chợ Chi Đông": { di: "Mê Linh", ec: 22 },
"1. Ha Noi_Chợ Quang Minh": { di: "Mê Linh", ec: 35 },
"1. Ha Noi_Chợ Hạ": { di: "Mê Linh", ec: 12 },
"1. Ha Noi_Chợ Hoa": { di: "Mê Linh", ec: 5 },
"1. Ha Noi_Chợ Đầu Đê": { di: "Mê Linh", ec: 6 },
"1. Ha Noi_Chợ Sặt": { di: "Mê Linh", ec: 10 },
"1. Ha Noi_Chợ Tế Tiêu": { di: "Mỹ Đức", ec: 35 },
"1. Ha Noi_Chợ Kênh Đào": { di: "Mỹ Đức", ec: 8 },
"1. Ha Noi_Chợ Sêu": { di: "Mỹ Đức", ec: 10 },
"1. Ha Noi_Chợ Thượng": { di: "Mỹ Đức", ec: 6 },
"1. Ha Noi_Chợ Hồng Sơn": { di: "Mỹ Đức", ec: 5 },
"1. Ha Noi_Chợ Vài": { di: "Mỹ Đức", ec: 14 },
"1. Ha Noi_Chợ Đục Khê": { di: "Mỹ Đức", ec: 20 },
"1. Ha Noi_Chợ Lai Thụ": { di: "Mỹ Đức", ec: 7 },
"1. Ha Noi_Chợ Phù Lưu Tế": { di: "Mỹ Đức", ec: 9 },
"1. Ha Noi_Chợ Xuy Xá": { di: "Mỹ Đức", ec: 8 },
"1. Ha Noi_Chợ Sáng Đại Mỗ": { di: "Nam Từ Liêm", ec: 10 },
"1. Ha Noi_Chợ Mỹ Đình": { di: "Nam Từ Liêm", ec: 30 },
"1. Ha Noi_Chợ Miêu Nha": { di: "Nam Từ Liêm", ec: 12 },
"1. Ha Noi_Chợ Phùng Khoang": { di: "Nam Từ Liêm", ec: 15 },
"1. Ha Noi_Chợ Thương Mại Dịch Vụ Tổng Hợp Trung Văn": { di: "Nam Từ Liêm", ec: 25 },
"1. Ha Noi_Chợ Trung Văn 1": { di: "Nam Từ Liêm", ec: 18 },
"1. Ha Noi_Chợ Thôn Trung Văn": { di: "Nam Từ Liêm", ec: 8 },
"1. Ha Noi_Chợ Nhổn": { di: "Nam Từ Liêm", ec: 40 },
"1. Ha Noi_Chợ Canh": { di: "Nam Từ Liêm", ec: 28 },
"1. Ha Noi_Chợ Phú Minh": { di: "Phú Xuyên", ec: 20 },
"1. Ha Noi_Chợ Lịm": { di: "Phú Xuyên", ec: 32 },
"1. Ha Noi_Chợ Phú Mỹ": { di: "Phú Xuyên", ec: 25 },
"1. Ha Noi_Chợ Hoà Khê": { di: "Phú Xuyên", ec: 6 },
"1. Ha Noi_Chợ Dâu": { di: "Phú Xuyên", ec: 8 },
"1. Ha Noi_Chợ Chuôn": { di: "Phú Xuyên", ec: 22 },
"1. Ha Noi_Chợ Đồng Vàng": { di: "Phú Xuyên", ec: 7 },
"1. Ha Noi_Chợ Bóng": { di: "Phú Xuyên", ec: 10 },
"1. Ha Noi_Chợ Khang": { di: "Phú Xuyên", ec: 9 },
"1. Ha Noi_Chợ Bái": { di: "Phú Xuyên", ec: 8 },
"1. Ha Noi_Chợ Phú Túc": { di: "Phú Xuyên", ec: 22 },
"1. Ha Noi_Chợ Giẽ": { di: "Phú Xuyên", ec: 24 },
"1. Ha Noi_Chợ An Khoái": { di: "Phú Xuyên", ec: 6 },
"1. Ha Noi_Chợ Chằm": { di: "Phú Xuyên", ec: 6 },
"1. Ha Noi_Chợ Tre": { di: "Phú Xuyên", ec: 10 },
"1. Ha Noi_Chợ Bìm ": { di: "Phú Xuyên", ec: 7 },
"1. Ha Noi_Chợ Chảy": { di: "Phú Xuyên", ec: 12 },
"1. Ha Noi_Chợ Võng Xuyên": { di: "Phúc Thọ", ec: 15 },
"1. Ha Noi_Chợ Bãi ": { di: "Phúc Thọ", ec: 8 },
"1. Ha Noi_Chợ Hát": { di: "Phúc Thọ", ec: 12 },
"1. Ha Noi_Chợ Tạm Liên Hiệp": { di: "Phúc Thọ", ec: 6 },
"1. Ha Noi_Chợ Triệu": { di: "Phúc Thọ", ec: 8 },
"1. Ha Noi_Chợ Ngọc Tảo": { di: "Phúc Thọ", ec: 14 },
"1. Ha Noi_Chợ Tạm Thôn Thanh Phần": { di: "Phúc Thọ", ec: 4 },
"1. Ha Noi_Chợ Tạm Thôn Thư Trai": { di: "Phúc Thọ", ec: 5 },
"1. Ha Noi_Chợ Sen Chiểu": { di: "Phúc Thọ", ec: 7 },
"1. Ha Noi_Chợ Hiệp": { di: "Phúc Thọ", ec: 28 },
"1. Ha Noi_Chợ Cát Hạ ": { di: "Phúc Thọ", ec: 5 },
"1. Ha Noi_Chợ Gạch": { di: "Phúc Thọ", ec: 12 },
"1. Ha Noi_Chợ Tạm Thượng Cốc": { di: "Phúc Thọ", ec: 4 },
"1. Ha Noi_Chợ Me": { di: "Phúc Thọ", ec: 8 },
"1. Ha Noi_Chợ Tạm Vân Nam": { di: "Phúc Thọ", ec: 5 },
"1. Ha Noi_Chợ Phủ Quốc": { di: "Quốc Oai", ec: 38 },
"1. Ha Noi_Chợ Bương": { di: "Quốc Oai", ec: 22 },
"1. Ha Noi_Chợ Cấn Thượng": { di: "Quốc Oai", ec: 6 },
"1. Ha Noi_Chợ Cổng Sy": { di: "Quốc Oai", ec: 5 },
"1. Ha Noi_Chợ Bồ Đề": { di: "Quốc Oai", ec: 8 },
"1. Ha Noi_Chợ Lập Thành": { di: "Quốc Oai", ec: 5 },
"1. Ha Noi_Chợ Long Phú": { di: "Quốc Oai", ec: 8 },
"1. Ha Noi_Chợ Đô Hội": { di: "Quốc Oai", ec: 7 },
"1. Ha Noi_Chợ Phú Cát": { di: "Quốc Oai", ec: 14 },
"1. Ha Noi_Chợ Thày": { di: "Quốc Oai", ec: 18 },
"1. Ha Noi_Chợ So": { di: "Quốc Oai", ec: 26 },
"1. Ha Noi_Chợ Tân Phú": { di: "Quốc Oai", ec: 8 },
"1. Ha Noi_Chợ Gồ": { di: "Quốc Oai", ec: 6 },
"1. Ha Noi_Chợ Sóc Sơn": { di: "Sóc Sơn", ec: 45 },
"1. Ha Noi_Chợ Yên Tàng": { di: "Sóc Sơn", ec: 8 },
"1. Ha Noi_Chợ Trấu": { di: "Sóc Sơn", ec: 6 },
"1. Ha Noi_Chợ Đa Hội": { di: "Sóc Sơn", ec: 5 },
"1. Ha Noi_Chợ Yêm": { di: "Sóc Sơn", ec: 5 },
"1. Ha Noi_Chợ Nam Cương": { di: "Sóc Sơn", ec: 8 },
"1. Ha Noi_Chợ Thái Phù": { di: "Sóc Sơn", ec: 14 },
"1. Ha Noi_Chợ Phú Cường": { di: "Sóc Sơn", ec: 12 },
"1. Ha Noi_Chợ Phù Lỗ": { di: "Sóc Sơn", ec: 30 },
"1. Ha Noi_Chợ Quang Tiến": { di: "Sóc Sơn", ec: 7 },
"1. Ha Noi_Chợ Tân Dân": { di: "Sóc Sơn", ec: 10 },
"1. Ha Noi_Chợ Thanh Nhàn": { di: "Sóc Sơn", ec: 6 },
"1. Ha Noi_Chợ Nỷ": { di: "Sóc Sơn", ec: 35 },
"1. Ha Noi_Chợ Thá": { di: "Sóc Sơn", ec: 7 },
"1. Ha Noi_Chợ Xuân Lai": { di: "Sóc Sơn", ec: 10 },
"1. Ha Noi_Chợ Phú Thịnh": { di: "Sơn Tây", ec: 12 },
"1. Ha Noi_Chợ Sơn Lộc": { di: "Sơn Tây", ec: 15 },
"1. Ha Noi_Chợ Ao Đông": { di: "Sơn Tây", ec: 10 },
"1. Ha Noi_Chợ Xuân Khanh": { di: "Sơn Tây", ec: 18 },
"1. Ha Noi_Chợ Trung Sơn Trầm": { di: "Sơn Tây", ec: 20 },
"1. Ha Noi_Chợ Bãi Đá": { di: "Sơn Tây", ec: 8 },
"1. Ha Noi_Chợ Mía": { di: "Sơn Tây", ec: 12 },
"1. Ha Noi_Chợ Kim Sơn": { di: "Sơn Tây", ec: 6 },
"1. Ha Noi_Chợ Sơn Đông": { di: "Sơn Tây", ec: 8 },
"1. Ha Noi_Chợ Vị Thuỷ": { di: "Sơn Tây", ec: 7 },
"1. Ha Noi_Chợ Tam Đa": { di: "Tây Hồ", ec: 8 },
"1. Ha Noi_Chợ Bưởi": { di: "Tây Hồ", ec: 25 },
"1. Ha Noi_Chợ Nhật Tân": { di: "Tây Hồ", ec: 16 },
"1. Ha Noi_Chợ Phú Gia": { di: "Tây Hồ", ec: 14 },
"1. Ha Noi_Chợ Dân Sinh Quảng An": { di: "Tây Hồ", ec: 10 },
"1. Ha Noi_Chợ Yên Phụ": { di: "Tây Hồ", ec: 15 },
"1. Ha Noi_Chợ Tứ Liên": { di: "Tây Hồ", ec: 12 },
"1. Ha Noi_Chợ Quảng An": { di: "Tây Hồ", ec: 2 },
"1. Ha Noi_Chợ Săn": { di: "Thạch Thất", ec: 35 },
"1. Ha Noi_Chợ Nủa": { di: "Thạch Thất", ec: 15 },
"1. Ha Noi_Chợ Hòa Lạc": { di: "Thạch Thất", ec: 20 },
"1. Ha Noi_Chợ Cẩm Yên": { di: "Thạch Thất", ec: 5 },
"1. Ha Noi_Chợ Canh Nậu": { di: "Thạch Thất", ec: 20 },
"1. Ha Noi_Chợ Chàng": { di: "Thạch Thất", ec: 22 },
"1. Ha Noi_Chợ Đại Đồng": { di: "Thạch Thất", ec: 10 },
"1. Ha Noi_Chợ Trúc Động": { di: "Thạch Thất", ec: 7 },
"1. Ha Noi_Chợ Roi": { di: "Thạch Thất", ec: 12 },
"1. Ha Noi_Chợ Hương Ngải": { di: "Thạch Thất", ec: 9 },
"1. Ha Noi_Chợ Hữu Bằng": { di: "Thạch Thất", ec: 25 },
"1. Ha Noi_Chợ Kim Quan": { di: "Thạch Thất", ec: 9 },
"1. Ha Noi_Chợ Lại Thượng": { di: "Thạch Thất", ec: 8 },
"1. Ha Noi_Chợ Bùng": { di: "Thạch Thất", ec: 24 },
"1. Ha Noi_Chợ Cầu Chùa": { di: "Thạch Thất", ec: 6 },
"1. Ha Noi_Chợ Gò Chói": { di: "Thạch Thất", ec: 5 },
"1. Ha Noi_Chợ Cò": { di: "Thạch Thất", ec: 5 },
"1. Ha Noi_Chợ Gốc Sui": { di: "Thạch Thất", ec: 4 },
"1. Ha Noi_Chợ Kim Bài": { di: "Thanh Oai", ec: 30 },
"1. Ha Noi_Chợ Thạch Bích": { di: "Thanh Oai", ec: 16 },
"1. Ha Noi_Chợ Bình Đà": { di: "Thanh Oai", ec: 22 },
"1. Ha Noi_Chợ Cao": { di: "Thanh Oai", ec: 10 },
"1. Ha Noi_Chợ Cao Bộ": { di: "Thanh Oai", ec: 7 },
"1. Ha Noi_Chợ Cự Đà": { di: "Thanh Oai", ec: 14 },
"1. Ha Noi_Chợ Vác": { di: "Thanh Oai", ec: 18 },
"1. Ha Noi_Chợ Văn Quán": { di: "Thanh Oai", ec: 6 },
"1. Ha Noi_Chợ Hoàng Trung": { di: "Thanh Oai", ec: 7 },
"1. Ha Noi_Chợ Đôn Thư": { di: "Thanh Oai", ec: 6 },
"1. Ha Noi_Chợ Từ Châu": { di: "Thanh Oai", ec: 8 },
"1. Ha Noi_Chợ Châu Mai": { di: "Thanh Oai", ec: 5 },
"1. Ha Noi_Chợ Chuông": { di: "Thanh Oai", ec: 25 },
"1. Ha Noi_Chợ Tam Hưng": { di: "Thanh Oai", ec: 12 },
"1. Ha Noi_Chợ Chi Lễ": { di: "Thanh Oai", ec: 8 },
"1. Ha Noi_Chợ Mai": { di: "Thanh Oai", ec: 8 },
"1. Ha Noi_Chợ Thanh Thuỳ": { di: "Thanh Oai", ec: 20 },
"1. Ha Noi_Chợ Nâu": { di: "Thanh Oai", ec: 5 },
"1. Ha Noi_Chợ Tttm-Thanh Trì": { di: "Thanh Trì", ec: 55 },
"1. Ha Noi_Chợ Tt Văn Điển": { di: "Thanh Trì", ec: 25 },
"1. Ha Noi_Chợ Đại Áng": { di: "Thanh Trì", ec: 9 },
"1. Ha Noi_Chợ Đông Mỹ": { di: "Thanh Trì", ec: 8 },
"1. Ha Noi_Chợ Duyên Hà": { di: "Thanh Trì", ec: 5 },
"1. Ha Noi_Chợ Hữu Hòa": { di: "Thanh Trì", ec: 8 },
"1. Ha Noi_Chợ Liên Ninh": { di: "Thanh Trì", ec: 10 },
"1. Ha Noi_Chợ Ngọc Hồi": { di: "Thanh Trì", ec: 18 },
"1. Ha Noi_Chợ Lạc Thị": { di: "Thanh Trì", ec: 6 },
"1. Ha Noi_Chợ Lưu Phái": { di: "Thanh Trì", ec: 8 },
"1. Ha Noi_Chợ Tương Chúc": { di: "Thanh Trì", ec: 5 },
"1. Ha Noi_Chợ Cầu Bươu": { di: "Thanh Trì", ec: 24 },
"1. Ha Noi_Chợ Tựu Liệt": { di: "Thanh Trì", ec: 10 },
"1. Ha Noi_Chợ Tam Hiệp": { di: "Thanh Trì", ec: 7 },
"1. Ha Noi_Chợ Triều Khúc": { di: "Thanh Trì", ec: 35 },
"1. Ha Noi_Chợ Yên Xá": { di: "Thanh Trì", ec: 14 },
"1. Ha Noi_Chợ Thanh Liệt": { di: "Thanh Trì", ec: 15 },
"1. Ha Noi_Chợ Tứ Hiệp": { di: "Thanh Trì", ec: 20 },
"1. Ha Noi_Chợ Thôn 2,3 Xã Vạn Phúc": { di: "Thanh Trì", ec: 5 },
"1. Ha Noi_Chợ Quỳnh Đô": { di: "Thanh Trì", ec: 15 },
"1. Ha Noi_Chợ Vĩnh Ninh": { di: "Thanh Trì", ec: 6 },
"1. Ha Noi_Chợ Khương Đình": { di: "Thanh Xuân", ec: 18 },
"1. Ha Noi_Chợ Kim Giang": { di: "Thanh Xuân", ec: 16 },
"1. Ha Noi_ Chợ Thanh Xuân Bắc": { di: "Thanh Xuân", ec: 22 },
"1. Ha Noi_Chợ Thượng Đình": { di: "Thanh Xuân", ec: 15 },
"1. Ha Noi_Chợ Nhân Chính": { di: "Thanh Xuân", ec: 20 },
"1. Ha Noi_Chợ Ba Lăng": { di: "Thường Tín", ec: 7 },
"1. Ha Noi_Chợ Giường": { di: "Thường Tín", ec: 16 },
"1. Ha Noi_Chợ Vồi": { di: "Thường Tín", ec: 35 },
"1. Ha Noi_Chợ Chiếc": { di: "Thường Tín", ec: 8 },
"1. Ha Noi_Chợ Hoà Bình": { di: "Thường Tín", ec: 5 },
"1. Ha Noi_Chợ Vân La": { di: "Thường Tín", ec: 8 },
"1. Ha Noi_Chợ Đỗ Hà": { di: "Thường Tín", ec: 7 },
"1. Ha Noi_Chợ Gia Cầm Hà Vĩ": { di: "Thường Tín", ec: 5 },
"1. Ha Noi_Chợ Liên Phương": { di: "Thường Tín", ec: 10 },
"1. Ha Noi_Chợ Que Hàn": { di: "Thường Tín", ec: 12 },
"1. Ha Noi_Chợ Kệ": { di: "Thường Tín", ec: 9 },
"1. Ha Noi_Chợ Tân Minh": { di: "Thường Tín", ec: 6 },
"1. Ha Noi_Chợ Trát Cầu": { di: "Thường Tín", ec: 18 },
"1. Ha Noi_Chợ Mui": { di: "Thường Tín", ec: 7 },
"1. Ha Noi_Chợ Bằng": { di: "Thường Tín", ec: 7 },
"1. Ha Noi_Chợ Đỗ Xá": { di: "Thường Tín", ec: 20 },
"1. Ha Noi_Chợ Quán Giai": { di: "Thường Tín", ec: 6 },
"1. Ha Noi_Chợ Nguộn": { di: "Thường Tín", ec: 8 },
"1. Ha Noi_Chợ Thôn Tử Dương": { di: "Ứng Hòa", ec: 6 },
"1. Ha Noi_Chợ Tía": { di: "Ứng Hòa", ec: 6 },
"1. Ha Noi_Chợ Ngăm": { di: "Ứng Hòa", ec: 6 },
"1. Ha Noi_Chợ Đông Lỗ": { di: "Ứng Hòa", ec: 5 },
"1. Ha Noi_Chợ Mỹ Cầu": { di: "Ứng Hòa", ec: 5 },
"1. Ha Noi_Chợ Cống Khê": { di: "Ứng Hòa", ec: 5 },
"1. Ha Noi_Chợ Đanh ": { di: "Ứng Hòa", ec: 8 },
"1. Ha Noi_Chợ Đặng Giang": { di: "Ứng Hòa", ec: 6 },
"1. Ha Noi_Chợ Lau ": { di: "Ứng Hòa", ec: 5 },
"1. Ha Noi_Chợ Hoà Xá": { di: "Ứng Hòa", ec: 15 },
"1. Ha Noi_Chợ Sậy": { di: "Ứng Hòa", ec: 7 },
"1. Ha Noi_Chợ Minh Đức": { di: "Ứng Hòa", ec: 7 },
"1. Ha Noi_Chợ Dầu Mới": { di: "Ứng Hòa", ec: 6 },
"1. Ha Noi_Chợ Phương Tú": { di: "Ứng Hòa", ec: 6 },
"1. Ha Noi_Chợ Xà Kiều": { di: "Ứng Hòa", ec: 7 },
"1. Ha Noi_Chợ Cầu Bầu": { di: "Ứng Hòa", ec: 22 },
"1. Ha Noi_Chợ Chòng": { di: "Ứng Hòa", ec: 8 },
"1. Ha Noi_Chợ Cháy": { di: "Ứng Hòa", ec: 14 },
"1. Ha Noi_Chợ Vạn Thái": { di: "Ứng Hòa", ec: 6 },
"1. Ha Noi_Chợ Ba Thá": { di: "Ứng Hòa", ec: 18 },
"1. Ha Noi_Chợ Vân": { di: "Ứng Hòa", ec: 5 },
"1. Ha Noi_Tạp Hóa-Ba Đình": { di: "Ba Đình", ec: 1 },
"1. Ha Noi_Tạp Hóa-Cầu Giấy": { di: "Cầu Giấy", ec: 1 },
"1. Ha Noi_Tạp Hóa-Đống Đa": { di: "Đống Đa", ec: 1 },
"1. Ha Noi_Tạp Hóa-Hà Đông": { di: "Hà Đông", ec: 1 },
"1. Ha Noi_Tạp Hóa-Hai Bà Trưng": { di: "Hai Bà Trưng", ec: 1 },
"1. Ha Noi_Tạp Hóa-Hoàn Kiếm": { di: "Hoàn Kiếm", ec: 1 },
"1. Ha Noi_Tạp Hóa-Hoàng Mai": { di: "Hoàng Mai", ec: 1 },
"1. Ha Noi_Tạp Hóa-Lĩnh Nam": { di: "Lĩnh Nam", ec: 1 },
"1. Ha Noi_Tạp Hóa-Nam Từ Liêm": { di: "Nam Từ Liêm", ec: 1 },
"1. Ha Noi_Tạp Hóa-Tây Hồ": { di: "Tây Hồ", ec: 1 },
"1. Ha Noi_Tạp Hóa-Thanh Liệt": { di: "Thanh Liệt", ec: 1 },
"1. Ha Noi_Tạp Hóa-Thanh Oai": { di: "Thanh Oai", ec: 1 },
"1. Ha Noi_Tạp Hóa-Thanh Trì": { di: "Thanh Trì", ec: 1 },
"1. Ha Noi_Tạp Hóa-Thanh Xuân": { di: "Thanh Xuân", ec: 1 },
"1. Ha Noi_Chợ Kim Liên": { di: "Đống Đa", ec: 15 },
"1. Ha Noi_Chợ An Dương": { di: "Tây Hồ", ec: 15 },
"1. Ha Noi_Chợ Dịch Vọng": { di: "Cầu Giấy", ec: 21 },
"1. Ha Noi_Chợ Kim Hoa": { di: "Đống Đa", ec: 8 },
"1. Ha Noi_Chợ Nam Đồng": { di: "Đống Đa", ec: 25 },
"1. Ha Noi_Chợ Ngô Sỹ Liên": { di: "Đống Đa", ec: 13 },
"1. Ha Noi_Chợ Phúc Xá": { di: "Ba Đình", ec: 10 },
"1. Ha Noi_Chợ Quang": { di: "Thanh Trì", ec: 22 },
"1. Ha Noi_Chợ Thành Công": { di: "Ba Đình", ec: 29 },
"1. Ha Noi_Chợ Thuý Lĩnh": { di: "Hoàng Mai", ec: 12 },
"1. Ha Noi_Chợ Tôn Đức Thắng": { di: "Đống Đa", ec: 15 },
"1. Ha Noi_Chợ Trần Duy Hưng": { di: "Cầu Giấy", ec: 19 },
"1. Ha Noi_Chợ Trung Kính": { di: "Cầu Giấy", ec: 15 },
"1. Ha Noi_Chợ Trung Phụng": { di: "Đống Đa", ec: 30 },
"1. Ha Noi_Chợ Trung Tự": { di: "Đống Đa", ec: 25 },
"1. Ha Noi_Chợ Văn Khê": { di: "Hà Đông", ec: 11 },
"1. Ha Noi_Chợ Vĩnh Phúc": { di: "Ba Đình", ec: 40 },
"1. Ha Noi_Chợ Yên Duyên": { di: "Hoàng Mai", ec: 7 },

"4. Eastern_Chợ An Bình": { di: "Biên Hòa", ec: 48 },
"4. Eastern_Chợ Phúc Lâm": { di: "Biên Hòa", ec: 18 },
"4. Eastern_Chợ Hội Am": { di: "Biên Hòa", ec: 16 },
"4. Eastern_Chợ Hóa An": { di: "Biên Hòa", ec: 60 },
"4. Eastern_Chợ K8 Long Bình": { di: "Biên Hòa", ec: 65 },
"4. Eastern_Chợ Trại Bò": { di: "Biên Hòa", ec: 22 },
"4. Eastern_Chợ Điều Long Bình": { di: "Biên Hòa", ec: 45 },
"4. Eastern_Chợ Cổng 11": { di: "Biên Hòa", ec: 55 },
"4. Eastern_Chợ Long Bình Tân": { di: "Biên Hòa", ec: 140 },
"4. Eastern_Chợ Ấp Tân Cảng Phước Tân": { di: "Biên Hòa", ec: 14 },
"4. Eastern_Chợ Tam Hòa": { di: "Biên Hòa", ec: 50 },
"4. Eastern_Chợ Thiên Bình": { di: "Biên Hòa", ec: 18 },
"4. Eastern_Chợ Tam Phước": { di: "Biên Hòa", ec: 48 },
"4. Eastern_Chợ Poh Huat": { di: "Biên Hòa", ec: 15 },
"4. Eastern_Chợ Sặt": { di: "Biên Hòa", ec: 250 },
"4. Eastern_Chợ Tân Biên": { di: "Biên Hòa", ec: 110 },
"4. Eastern_Chợ Nhỏ Tân Hiệp": { di: "Biên Hòa", ec: 12 },
"4. Eastern_Chợ Thái Bình": { di: "Biên Hòa", ec: 52 },
"4. Eastern_Chợ Nhỏ Lộ Đức": { di: "Biên Hòa", ec: 11 },
"4. Eastern_Chợ Tân Phong": { di: "Biên Hòa", ec: 50 },
"4. Eastern_Chợ Biên Hòa": { di: "Biên Hòa", ec: 220 },
"4. Eastern_Chợ Bảo Bình": { di: "Cẩm Mỹ", ec: 15 },
"4. Eastern_Chợ Chiều Cầu 4": { di: "Cẩm Mỹ", ec: 12 },
"4. Eastern_Chợ Nhân Nghĩa": { di: "Cẩm Mỹ", ec: 45 },
"4. Eastern_Chợ Thừa Đức": { di: "Cẩm Mỹ", ec: 15 },
"4. Eastern_Chợ Nam Hà": { di: "Cẩm Mỹ", ec: 11 },
"4. Eastern_Chợ Xuân Bảo": { di: "Cẩm Mỹ", ec: 14 },
"4. Eastern_Chợ Láng Me": { di: "Cẩm Mỹ", ec: 12 },
"4. Eastern_Chợ Xuân Mỹ": { di: "Cẩm Mỹ", ec: 16 },
"4. Eastern_Chợ Xuân Quế": { di: "Cẩm Mỹ", ec: 15 },
"4. Eastern_Chợ Xuân Tây": { di: "Cẩm Mỹ", ec: 42 },
"4. Eastern_Chợ Định Quán": { di: "Định Quán", ec: 130 },
"4. Eastern_Chợ Gia Canh": { di: "Định Quán", ec: 16 },
"4. Eastern_Chợ La Ngà": { di: "Định Quán", ec: 55 },
"4. Eastern_Chợ Phú Hòa": { di: "Định Quán", ec: 14 },
"4. Eastern_Chợ Phú Lợi": { di: "Định Quán", ec: 48 },
"4. Eastern_Chợ Cũ Phú Vinh": { di: "Định Quán", ec: 12 },
"4. Eastern_Chợ Phú Tân": { di: "Định Quán", ec: 15 },
"4. Eastern_Chợ Ba Lưới": { di: "Định Quán", ec: 11 },
"4. Eastern_Chợ Phú Cường": { di: "Định Quán", ec: 45 },
"4. Eastern_Chợ Phú Túc": { di: "Định Quán", ec: 48 },
"4. Eastern_Chợ Phú Vinh": { di: "Định Quán", ec: 52 },
"4. Eastern_Chợ Suối Nho": { di: "Định Quán", ec: 55 },
"4. Eastern_Chợ Bàu Cối": { di: "Long Khánh", ec: 14 },
"4. Eastern_Chợ Bảo Vinh": { di: "Long Khánh", ec: 45 },
"4. Eastern_Chợ Bình Lộc": { di: "Long Khánh", ec: 18 },
"4. Eastern_Chợ Phú Bình": { di: "Long Khánh", ec: 12 },
"4. Eastern_Chợ Đêm Long Khánh": { di: "Long Khánh", ec: 40 },
"4. Eastern_Chợ An Lộc": { di: "Long Khánh", ec: 16 },
"4. Eastern_Chợ Xuân Thanh": { di: "Long Khánh", ec: 60 },
"4. Eastern_Chợ Long Khánh": { di: "Long Khánh", ec: 180 },
"4. Eastern_Chợ Cự Thành": { di: "Long Thành", ec: 11 },
"4. Eastern_Chợ Bàu Cạn": { di: "Long Thành", ec: 42 },
"4. Eastern_Chợ Bình Sơn": { di: "Long Thành", ec: 52 },
"4. Eastern_Chợ Suối Quýt": { di: "Long Thành", ec: 10 },
"4. Eastern_Chợ Tái Định Cư Bình Sơn": { di: "Long Thành", ec: 45 },
"4. Eastern_Chợ Lộc An": { di: "Long Thành", ec: 15 },
"4. Eastern_Chợ 67- Chợ PhướC Hoà": { di: "Long Thành", ec: 48 },
"4. Eastern_Chợ Long Thành": { di: "Long Thành", ec: 150 },
"4. Eastern_Chợ Đêm Long Thành": { di: "Long Thành", ec: 35 },
"4. Eastern_Chợ Phước Bình": { di: "Long Thành", ec: 50 },
"4. Eastern_Chợ Long Phú Mới": { di: "Long Thành", ec: 45 },
"4. Eastern_Chợ Tạm Phước Lý": { di: "Nhơn Trạch", ec: 15 },
"4. Eastern_Chợ Đại Phước": { di: "Nhơn Trạch", ec: 65 },
"4. Eastern_Chợ Đêm Hiệp Phước": { di: "Nhơn Trạch", ec: 30 },
"4. Eastern_Chợ Long Thọ": { di: "Nhơn Trạch", ec: 55 },
"4. Eastern_Chợ Giồng Ông Đông": { di: "Nhơn Trạch", ec: 14 },
"4. Eastern_Chợ Chiều Phú Hội": { di: "Nhơn Trạch", ec: 20 },
"4. Eastern_Chợ Sáng Phú Hội": { di: "Nhơn Trạch", ec: 15 },
"4. Eastern_Chợ Tạm Phú Mỹ 1": { di: "Nhơn Trạch", ec: 12 },
"4. Eastern_Chợ Phước An": { di: "Nhơn Trạch", ec: 45 },
"4. Eastern_Chợ Vũng Gấm": { di: "Nhơn Trạch", ec: 14 },
"4. Eastern_Chợ Bắc": { di: "Nhơn Trạch", ec: 11 },
"4. Eastern_Chợ Mới Biên Hùng": { di: "Nhơn Trạch", ec: 50 },
"4. Eastern_Chợ Bến Cam": { di: "Nhơn Trạch", ec: 65 },
"4. Eastern_Chợ Bắc Minh": { di: "Nhơn Trạch", ec: 15 },
"4. Eastern_Chợ Hòa Bình": { di: "Nhơn Trạch", ec: 12 },
"4. Eastern_Chợ Mới Phú Điền": { di: "Tân Phú", ec: 14 },
"4. Eastern_Chợ Phương Lâm": { di: "Tân Phú", ec: 150 },
"4. Eastern_Chợ Phú Lập": { di: "Tân Phú", ec: 15 },
"4. Eastern_Chợ Phú Lộc": { di: "Tân Phú", ec: 12 },
"4. Eastern_Chợ Số 10": { di: "Tân Phú", ec: 10 },
"4. Eastern_Chợ Huyện Tân Phú": { di: "Tân Phú", ec: 130 },
"4. Eastern_Chợ Dầu Giây": { di: "Thống Nhất", ec: 120 },
"4. Eastern_Chợ Phan Bội Châu": { di: "Thống Nhất", ec: 18 },
"4. Eastern_Chợ 94": { di: "Thống Nhất", ec: 11 },
"4. Eastern_Chợ Dốc Mơ": { di: "Thống Nhất", ec: 55 },
"4. Eastern_Chợ Bạch Lâm": { di: "Thống Nhất", ec: 48 },
"4. Eastern_Chợ Hưng Nghĩa": { di: "Thống Nhất", ec: 15 },
"4. Eastern_Chợ Hưng Lộc": { di: "Thống Nhất", ec: 16 },
"4. Eastern_Chợ Tân Lập": { di: "Thống Nhất", ec: 10 },
"4. Eastern_Chợ Nguyễn Huệ": { di: "Thống Nhất", ec: 52 },
"4. Eastern_Chợ Mới Phú Sơn": { di: "Trảng Bom", ec: 45 },
"4. Eastern_Chợ Bắc Hòa": { di: "Trảng Bom", ec: 48 },
"4. Eastern_Chợ Chiều Sông Mây": { di: "Trảng Bom", ec: 55 },
"4. Eastern_Chợ Bắc Hợp": { di: "Trảng Bom", ec: 22 },
"4. Eastern_Chợ Bàu Hàm": { di: "Trảng Bom", ec: 15 },
"4. Eastern_Chợ Tân Bắc": { di: "Trảng Bom", ec: 50 },
"4. Eastern_Chợ Trà Cổ": { di: "Trảng Bom", ec: 14 },
"4. Eastern_Chợ Cây Gáo": { di: "Trảng Bom", ec: 42 },
"4. Eastern_Chợ Hố Nai 3": { di: "Trảng Bom", ec: 130 },
"4. Eastern_Chợ Sông Thao": { di: "Trảng Bom", ec: 15 },
"4. Eastern_Chợ Sông Trầu": { di: "Trảng Bom", ec: 45 },
"4. Eastern_Chợ Số 9": { di: "Trảng Bom", ec: 11 },
"4. Eastern_Chợ Lộc Hòa": { di: "Trảng Bom", ec: 16 },
"4. Eastern_Chợ Trường An": { di: "Trảng Bom", ec: 10 },
"4. Eastern_Chợ Mới Trảng Bom": { di: "Trảng Bom", ec: 150 },
"4. Eastern_Chợ Mã Đà": { di: "Vĩnh Cửu", ec: 8 },
"4. Eastern_Chợ Tân Bình": { di: "Vĩnh Cửu", ec: 14 },
"4. Eastern_Chợ Vĩnh Cửu": { di: "Vĩnh Cửu", ec: 65 },
"4. Eastern_Chợ Vĩnh An": { di: "Vĩnh Cửu", ec: 110 },
"4. Eastern_Chợ Khu Phố 1": { di: "Vĩnh Cửu", ec: 16 },
"4. Eastern_Chợ Ấp 1 ": { di: "Vĩnh Cửu", ec: 15 },
"4. Eastern_Chợ Vĩnh Tân": { di: "Vĩnh Cửu", ec: 45 },
"4. Eastern_Chợ Bảo Hoà": { di: "Xuân Lộc", ec: 16 },
"4. Eastern_Chợ Ông Đồn": { di: "Xuân Lộc", ec: 55 },
"4. Eastern_Chợ Huyện Xuân Lộc": { di: "Xuân Lộc", ec: 140 },
"4. Eastern_Chợ Lang Minh": { di: "Xuân Lộc", ec: 15 },
"4. Eastern_Chợ Suối Cát": { di: "Xuân Lộc", ec: 42 },
"4. Eastern_Chợ Xuân Bắc": { di: "Xuân Lộc", ec: 14 },
"4. Eastern_Chợ Xuân Hòa": { di: "Xuân Lộc", ec: 12 },
"4. Eastern_Chợ Xuân Hưng": { di: "Xuân Lộc", ec: 48 },
"4. Eastern_Chợ Năm Lò": { di: "Xuân Lộc", ec: 10 },
"4. Eastern_Chợ Bình Hòa": { di: "Xuân Lộc", ec: 16 },
"4. Eastern_Chợ Xuân Đà": { di: "Xuân Lộc", ec: 15 },
"4. Eastern_Chợ Xuân Thành - Huyện Xuân Lộc": { di: "Xuân Lộc", ec: 46 },
"4. Eastern_Chợ Xuân Lữ": { di: "Xuân Lộc", ec: 11 },
"4. Eastern_Chợ Xuân Thọ": { di: "Xuân Lộc", ec: 12 },
"4. Eastern_Chợ Gia Ray": { di: "Xuân Lộc", ec: 50 },
"4. Eastern_Tạp Hóa-Trảng Bom": { di: "Trảng Bom", ec: 1 },
"4. Eastern_Chợ Bến Gỗ": { di: "Long Thành", ec: 20 },
"4. Eastern_Chợ Bửu Hòa": { di: "Biên Hòa", ec: 40 },
"4. Eastern_Chợ Đông Hòa": { di: "Trảng Bom", ec: 15 },
"4. Eastern_Chợ Gia Viên": { di: "Biên Hòa", ec: 15 },
"4. Eastern_Chợ Hoá An": { di: "Biên Hòa", ec: 25 },
"4. Eastern_Chợ Phú Sơn": { di: "Trảng Bom", ec: 20 },
"4. Eastern_Chợ Phước Tân": { di: "Long Thành", ec: 8 },
"4. Eastern_Chợ Quảng Biên": { di: "Trảng Bom", ec: 8 },
"4. Eastern_Chợ Quảng Tiến": { di: "Trảng Bom", ec: 6 },
"4. Eastern_Chợ Sông Mây": { di: "Trảng Bom", ec: 15 },
"4. Eastern_Chợ Tân Hiệp": { di: "Biên Hòa", ec: 55 },
"4. Eastern_Chợ Tân Mai": { di: "Biên Hòa", ec: 30 },
"4. Eastern_Chợ Thanh Hoá": { di: "Biên Hòa", ec: 10 },
"4. Eastern_Chợ Thạnh Phú": { di: "Vĩnh Cửu", ec: 20 },
"4. Eastern_Chợ Trảng Dài": { di: "Biên Hòa", ec: 55 },
"4. Eastern_Chợ Việt Giai": { di: "Trảng Bom", ec: 6 },
"4. Eastern_Tạp Hóa-Biên Hòa": { di: "Biên Hòa", ec: 1 },
"4. Eastern_Tạp Hóa- Long Thành": { di: "Long Thành", ec: 1 },
"4. Eastern_Tạp Hóa-Vĩnh Cửu": { di: "Vĩnh Cửu", ec: 1 },

};
