// dbMarket.js
const dbMarket = {
  "1. HCMC_Chợ Bà Lát": { di: "Bình Chánh", ec: 5 },
"1. HCMC_Chợ Bình Chánh": { di: "Bình Chánh", ec: 10 },
"1. HCMC_Chợ Cầu Xáng": { di: "Bình Chánh", ec: 5 },
"1. HCMC_Chợ Đệm": { di: "Bình Chánh", ec: 5 },
"1. HCMC_Chợ Hưng Long": { di: "Bình Chánh", ec: 5 },
"1. HCMC_Chợ Lê Minh Xuân": { di: "Bình Chánh", ec: 5 },
"1. HCMC_Chợ Vĩnh Lộc": { di: "Bình Chánh", ec: 15 },
"1. HCMC_Chợ Vĩnh Lộc A": { di: "Bình Chánh", ec: 8 },
"1. HCMC_Chợ Vĩnh Lộc B": { di: "Bình Chánh", ec: 8 },
"1. HCMC_Chợ An Lạc": { di: "Bình Tân", ec: 5 },
"1. HCMC_Chợ Bà Hom": { di: "Bình Tân", ec: 5 },
"1. HCMC_Chợ Bình Hưng Hoà": { di: "Bình Tân", ec: 11 },
"1. HCMC_Chợ Bình Long": { di: "Bình Tân", ec: 9 },
"1. HCMC_Chợ Bình Thành": { di: "Bình Tân", ec: 8 },
"1. HCMC_Chợ Bình Trị Đông": { di: "Bình Tân", ec: 20 },
"1. HCMC_Chợ Đất Mới": { di: "Bình Tân", ec: 5 },
"1. HCMC_Chợ Dĩa Tân Tạo": { di: "Bình Tân", ec: 7 },
"1. HCMC_Chợ Gò Xoài": { di: "Bình Tân", ec: 8 },
"1. HCMC_Chợ Kênh 19/5": { di: "Bình Tân", ec: 4 },
"1. HCMC_Chợ Khu Phố 2": { di: "Bình Tân", ec: 5 },
"1. HCMC_Chợ Kiến Đức": { di: "Bình Tân", ec: 5 },
"1. HCMC_Chợ Lê Đình Cẩn": { di: "Bình Tân", ec: 6 },
"1. HCMC_Chợ Ngã Tư Bốn Xã": { di: "Bình Tân", ec: 8 },
"1. HCMC_Chợ Phạm Đăng Giảng": { di: "Bình Tân", ec: 8 },
"1. HCMC_Chợ Bà Chiểu": { di: "Bình Thạnh", ec: 40 },
"1. HCMC_Chợ Cây Quéo": { di: "Bình Thạnh", ec: 12 },
"1. HCMC_Chợ Chiều Võ Duy Ninh": { di: "Bình Thạnh", ec: 7 },
"1. HCMC_Chợ Phan Văn Trị": { di: "Bình Thạnh", ec: 7 },
"1. HCMC_Chợ Phường 25": { di: "Bình Thạnh", ec: 11 },
"1. HCMC_Chợ Tạm Nguyễn Xí": { di: "Bình Thạnh", ec: 5 },
"1. HCMC_Chợ Thanh Đa": { di: "Bình Thạnh", ec: 10 },
"1. HCMC_Chợ Thị Nghè": { di: "Bình Thạnh", ec: 22 },
"1. HCMC_Chợ Vạn Kiếp": { di: "Bình Thạnh", ec: 8 },
"1. HCMC_Chợ Văn Thánh": { di: "Bình Thạnh", ec: 8 },
"1. HCMC_Bình Khánh": { di: "Cần Giờ", ec: 8 },
"1. HCMC_Chợ An Thới Đông": { di: "Cần Giờ", ec: 5 },
"1. HCMC_Chợ Đồng Hòa": { di: "Cần Giờ", ec: 2 },
"1. HCMC_Chợ Hòa Hiệp": { di: "Cần Giờ", ec: 2 },
"1. HCMC_Chợ Lý Nhơn": { di: "Cần Giờ", ec: 2 },
"1. HCMC_Chợ Bình Mỹ": { di: "Củ Chi", ec: 5 },
"1. HCMC_Chợ Củ Chi": { di: "Củ Chi", ec: 10 },
"1. HCMC_Chợ Tân Phú Trung": { di: "Củ Chi", ec: 15 },
"1. HCMC_Chợ Tân Thạnh Đông": { di: "Củ Chi", ec: 5 },
"1. HCMC_Chợ Tân Thông Hội": { di: "Củ Chi", ec: 14 },
"1. HCMC_Chợ Trung An": { di: "Củ Chi", ec: 5 },
"1. HCMC_Phú Hòa Đông": { di: "Củ Chi", ec: 5 },
"1. HCMC_Chợ An Hội": { di: "Gò Vấp", ec: 4 },
"1. HCMC_Chợ An Nhơn": { di: "Gò Vấp", ec: 8 },
"1. HCMC_Chợ Căn Cứ": { di: "Gò Vấp", ec: 15 },
"1. HCMC_Chợ Gò Vấp": { di: "Gò Vấp", ec: 13 },
"1. HCMC_Chợ Hạnh Thông Tây": { di: "Gò Vấp", ec: 5 },
"1. HCMC_Chợ Tân Sơn Nhất": { di: "Gò Vấp", ec: 12 },
"1. HCMC_Chợ Thạch Đà": { di: "Gò Vấp", ec: 10 },
"1. HCMC_Chợ Xóm Mới": { di: "Gò Vấp", ec: 4 },
"1. HCMC_Chợ Bà Điểm": { di: "Hóc Môn", ec: 6 },
"1. HCMC_Chợ Bùi Môn": { di: "Hóc Môn", ec: 4 },
"1. HCMC_Chợ Cây Me": { di: "Hóc Môn", ec: 7 },
"1. HCMC_Chợ Đông Thạnh": { di: "Hóc Môn", ec: 5 },
"1. HCMC_Chợ Hóc Môn": { di: "Hóc Môn", ec: 14 },
"1. HCMC_Chợ Nhị Xuân": { di: "Hóc Môn", ec: 4 },
"1. HCMC_Chợ Tạm Tân Hiệp": { di: "Hóc Môn", ec: 3 },
"1. HCMC_Chợ Tân Thới Nhì": { di: "Hóc Môn", ec: 4 },
"1. HCMC_Chợ Trần Văn Mười": { di: "Hóc Môn", ec: 4 },
"1. HCMC_Chợ Trung Chánh": { di: "Hóc Môn", ec: 12 },
"1. HCMC_Chợ Xuân Thới Thượng": { di: "Hóc Môn", ec: 8 },
"1. HCMC_Chợ Ấp 3": { di: "Nhà Bè", ec: 2 },
"1. HCMC_Chợ Bà Chồi": { di: "Nhà Bè", ec: 5 },
"1. HCMC_Chợ Bờ Băng": { di: "Nhà Bè", ec: 2 },
"1. HCMC_Chợ Cầu Kinh": { di: "Nhà Bè", ec: 3 },
"1. HCMC_Chợ Nhơn Đức": { di: "Nhà Bè", ec: 3 },
"1. HCMC_Chợ Phú Lễ": { di: "Nhà Bè", ec: 5 },
"1. HCMC_Chợ Phú Xuân": { di: "Nhà Bè", ec: 5 },
"1. HCMC_Chợ Phước Lộc": { di: "Nhà Bè", ec: 2 },
"1. HCMC_Chợ Tạm Phước Kiểng": { di: "Nhà Bè", ec: 7 },
"1. HCMC_Chợ Cô Giang": { di: "Phú Nhuận", ec: 4 },
"1. HCMC_Chợ Ga": { di: "Phú Nhuận", ec: 5 },
"1. HCMC_Chợ Nguyễn Đình Chiểu": { di: "Phú Nhuận", ec: 24 },
"1. HCMC_Chợ Phú Nhuận": { di: "Phú Nhuận", ec: 28 },
"1. HCMC_Chợ Trần Hữu Trang": { di: "Phú Nhuận", ec: 15 },
"1. HCMC_Chợ Bến Thành": { di: "Quận 1", ec: 8 },
"1. HCMC_Chợ Cầu Kho": { di: "Quận 1", ec: 5 },
"1. HCMC_Chợ Cầu Ông Lãnh": { di: "Quận 1", ec: 5 },
"1. HCMC_Chợ Đakao": { di: "Quận 1", ec: 8 },
"1. HCMC_Chợ Tân Định": { di: "Quận 1", ec: 28 },
"1. HCMC_Chợ Thái Bình": { di: "Quận 1", ec: 25 },
"1. HCMC_Chợ Tôn Thất Đạm": { di: "Quận 1", ec: 12 },
"1. HCMC_Chợ Yersin": { di: "Quận 1", ec: 7 },
"1. HCMC_Chợ Chí Hòa": { di: "Quận 10", ec: 6 },
"1. HCMC_Chợ Da Bà Bầu ": { di: "Quận 10", ec: 7 },
"1. HCMC_Chợ Hồ Thị Kỷ": { di: "Quận 10", ec: 5 },
"1. HCMC_Chợ Hòa Hưng": { di: "Quận 10", ec: 10 },
"1. HCMC_Chợ Lê Hồng Phong": { di: "Quận 10", ec: 8 },
"1. HCMC_Chợ Nguyễn Tri Phương": { di: "Quận 10", ec: 19 },
"1. HCMC_Chợ Nhật Tảo": { di: "Quận 10", ec: 6 },
"1. HCMC_Chợ Phường 10": { di: "Quận 10", ec: 4 },
"1. HCMC_Chợ Phường 2": { di: "Quận 10", ec: 4 },
"1. HCMC_Chợ Bình Thới": { di: "Quận 11", ec: 18 },
"1. HCMC_Chợ Chim Xanh": { di: "Quận 11", ec: 12 },
"1. HCMC_Chợ Hà Tôn Quyền": { di: "Quận 11", ec: 8 },
"1. HCMC_Chợ Lãnh Binh Thăng": { di: "Quận 11", ec: 12 },
"1. HCMC_Chợ Nhỏ Tự Phát": { di: "Quận 11", ec: 3 },
"1. HCMC_Chợ Phú Thọ": { di: "Quận 11", ec: 8 },
"1. HCMC_Chợ Thiếc": { di: "Quận 11", ec: 7 },
"1. HCMC_Chợ An Phú Đông": { di: "Quận 12", ec: 8 },
"1. HCMC_Chợ An Sương": { di: "Quận 12", ec: 16 },
"1. HCMC_Chợ Cầu": { di: "Quận 12", ec: 10 },
"1. HCMC_Chợ Chiều Tô Ký": { di: "Quận 12", ec: 4 },
"1. HCMC_Chợ Đông Quang": { di: "Quận 12", ec: 3 },
"1. HCMC_Chợ Giãn Dân": { di: "Quận 12", ec: 4 },
"1. HCMC_Chợ Hạt Điều": { di: "Quận 12", ec: 4 },
"1. HCMC_Chợ Hiệp Thành": { di: "Quận 12", ec: 8 },
"1. HCMC_Chợ Lạc Quang": { di: "Quận 12", ec: 9 },
"1. HCMC_Chợ Minh Phát": { di: "Quận 12", ec: 5 },
"1. HCMC_Chợ Nam Long": { di: "Quận 12", ec: 5 },
"1. HCMC_Chợ Ngã Ba Bầu": { di: "Quận 12", ec: 5 },
"1. HCMC_Chợ Tạm Cây Sộp": { di: "Quận 12", ec: 4 },
"1. HCMC_Chợ Tạm Thới An": { di: "Quận 12", ec: 5 },
"1. HCMC_Chợ Tạm Vườn Lài": { di: "Quận 12", ec: 6 },
"1. HCMC_Chợ Tân Chánh Hiệp": { di: "Quận 12", ec: 10 },
"1. HCMC_Chợ Thạnh Lộc": { di: "Quận 12", ec: 4 },
"1. HCMC_Chợ Thạnh Xuân": { di: "Quận 12", ec: 9 },
"1. HCMC_Chợ Thới An": { di: "Quận 12", ec: 4 },
"1. HCMC_Chợ Tô Ký": { di: "Quận 12", ec: 2 },
"1. HCMC_Chợ Việt Hưng": { di: "Quận 12", ec: 4 },
"1. HCMC_Chợ Vườn Lài": { di: "Quận 12", ec: 15 },
"1. HCMC_Chợ Bàn Cờ": { di: "Quận 3", ec: 12 },
"1. HCMC_Chợ Bùi Phát": { di: "Quận 3", ec: 4 },
"1. HCMC_Chợ Lê Văn Sỹ": { di: "Quận 3", ec: 7 },
"1. HCMC_Chợ Nguyễn Văn Trỗi": { di: "Quận 3", ec: 18 },
"1. HCMC_Chợ Vườn Chuối": { di: "Quận 3", ec: 6 },
"1. HCMC_Chợ 200": { di: "Quận 4", ec: 5 },
"1. HCMC_Chợ Cầu Cống": { di: "Quận 4", ec: 5 },
"1. HCMC_Chợ Đường Đoàn Văn Bơ": { di: "Quận 4", ec: 13 },
"1. HCMC_Chợ Hãng Dệt": { di: "Quận 4", ec: 3 },
"1. HCMC_Chợ Hãng Phân": { di: "Quận 4", ec: 5 },
"1. HCMC_Chợ Kho 11": { di: "Quận 4", ec: 3 },
"1. HCMC_Chợ Long Kiểng": { di: "Quận 4", ec: 5 },
"1. HCMC_Chợ Nguyễn Khoái": { di: "Quận 4", ec: 5 },
"1. HCMC_Chợ Tôn Thất Thuyết": { di: "Quận 4", ec: 4 },
"1. HCMC_Chợ Xóm Chiếu": { di: "Quận 4", ec: 20 },
"1. HCMC_Chợ An Đông": { di: "Quận 5", ec: 5 },
"1. HCMC_Chợ Bầu Sen": { di: "Quận 5", ec: 4 },
"1. HCMC_Chợ Cao Đạt": { di: "Quận 5", ec: 5 },
"1. HCMC_Chợ Hòa Bình": { di: "Quận 5", ec: 25 },
"1. HCMC_Chợ Phùng Hưng": { di: "Quận 5", ec: 4 },
"1. HCMC_Chợ Thuận Kiều": { di: "Quận 5", ec: 5 },
"1. HCMC_Chợ Thực Phẩm An Đông": { di: "Quận 5", ec: 9 },
"1. HCMC_Chợ Xã Tây": { di: "Quận 5", ec: 5 },
"1. HCMC_Chợ Xóm Vôi": { di: "Quận 5", ec: 6 },
"1. HCMC_Chợ An Dương Vương": { di: "Quận 6", ec: 4 },
"1. HCMC_Chợ Bình Tây": { di: "Quận 6", ec: 45 },
"1. HCMC_Chợ Bình Tiên": { di: "Quận 6", ec: 12 },
"1. HCMC_Chợ Hồ Trọng Quý": { di: "Quận 6", ec: 5 },
"1. HCMC_Chợ Lê Tấn Kế": { di: "Quận 6", ec: 25 },
"1. HCMC_Chợ Lò Gốm": { di: "Quận 6", ec: 4 },
"1. HCMC_Chợ Minh Phụng": { di: "Quận 6", ec: 4 },
"1. HCMC_Chợ Phú Định": { di: "Quận 6", ec: 8 },
"1. HCMC_Chợ Phú Lâm": { di: "Quận 6", ec: 18 },
"1. HCMC_Chợ Tân Hoà Đông": { di: "Quận 6", ec: 3 },
"1. HCMC_Chợ Trần Bình": { di: "Quận 6", ec: 20 },
"1. HCMC_Chợ Cư Xá Ngân Hàng": { di: "Quận 7", ec: 4 },
"1. HCMC_Chợ Gò Ô Môi": { di: "Quận 7", ec: 4 },
"1. HCMC_Chợ Phú Thuận": { di: "Quận 7", ec: 4 },
"1. HCMC_Chợ Phước Long": { di: "Quận 7", ec: 4 },
"1. HCMC_Chợ Rạch Đĩa": { di: "Quận 7", ec: 4 },
"1. HCMC_Chợ Tạm Bùi Văn Ba": { di: "Quận 7", ec: 4 },
"1. HCMC_Chợ Tân Kiểng 1": { di: "Quận 7", ec: 6 },
"1. HCMC_Chợ Tân Kiểng 2": { di: "Quận 7", ec: 6 },
"1. HCMC_Chợ Tân Mỹ ": { di: "Quận 7", ec: 6 },
"1. HCMC_Chợ Tân Quy": { di: "Quận 7", ec: 6 },
"1. HCMC_Chợ Tân Thuận": { di: "Quận 7", ec: 4 },
"1. HCMC_Chợ Tân Thuận Đông": { di: "Quận 7", ec: 4 },
"1. HCMC_Chợ Ba Đình": { di: "Quận 8", ec: 4 },
"1. HCMC_Chợ Bến Bình Đông": { di: "Quận 8", ec: 10 },
"1. HCMC_Chợ Bình An": { di: "Quận 8", ec: 3 },
"1. HCMC_Chợ Bình Điền": { di: "Quận 8", ec: 30 },
"1. HCMC_Chợ Bình Đông": { di: "Quận 8", ec: 4 },
"1. HCMC_Chợ Hưng Phú": { di: "Quận 8", ec: 4 },
"1. HCMC_Chợ Lò Than": { di: "Quận 8", ec: 5 },
"1. HCMC_Chợ Nguyễn Chế Nghĩa": { di: "Quận 8", ec: 4 },
"1. HCMC_Chợ Nhị Thiên Đường": { di: "Quận 8", ec: 8 },
"1. HCMC_Chợ Phạm Thế Hiển": { di: "Quận 8", ec: 10 },
"1. HCMC_Chợ Phú Lợi 2": { di: "Quận 8", ec: 2 },
"1. HCMC_Chợ Rạch Cát": { di: "Quận 8", ec: 4 },
"1. HCMC_Chợ Rạch Ông": { di: "Quận 8", ec: 18 },
"1. HCMC_Chợ Trần Văn Thành": { di: "Quận 8", ec: 4 },
"1. HCMC_Chợ Vạn Nguyên": { di: "Quận 8", ec: 3 },
"1. HCMC_Chợ Xóm Củi": { di: "Quận 8", ec: 12 },
"1. HCMC_Phú Định": { di: "Quận 8", ec: 3 },
"1. HCMC_Chợ Gò Công": { di: "Quận 9", ec: 4 },
"1. HCMC_Chợ Hiệp Phú": { di: "Quận 9", ec: 8 },
"1. HCMC_Chợ Hoa Cau": { di: "Quận 9", ec: 2 },
"1. HCMC_Chợ Kiến Thiết": { di: "Quận 9", ec: 5 },
"1. HCMC_Chợ Long Phước": { di: "Quận 9", ec: 4 },
"1. HCMC_Chợ Long Thạnh Mỹ": { di: "Quận 9", ec: 4 },
"1. HCMC_Chợ Long Trường": { di: "Quận 9", ec: 6 },
"1. HCMC_Chợ Nam Hoà ( Phước Long A)": { di: "Quận 9", ec: 4 },
"1. HCMC_Chợ Phước Bình": { di: "Quận 9", ec: 14 },
"1. HCMC_Chợ Phước Long B": { di: "Quận 9", ec: 4 },
"1. HCMC_Chợ Tăng Nhơn Phú A": { di: "Quận 9", ec: 6 },
"1. HCMC_Chợ Tăng Nhơn Phú B": { di: "Quận 9", ec: 6 },
"1. HCMC_Chợ Tây Hòa": { di: "Quận 9", ec: 2 },
"1. HCMC_Chợ Bà Hoa": { di: "Tân Bình", ec: 11 },
"1. HCMC_Chợ Bảo Ngọc Tú": { di: "Tân Bình", ec: 4 },
"1. HCMC_Chợ Bàu Cát": { di: "Tân Bình", ec: 4 },
"1. HCMC_Chợ Hoàng Hoa Thám": { di: "Tân Bình", ec: 18 },
"1. HCMC_Chợ Nam Hòa": { di: "Tân Bình", ec: 6 },
"1. HCMC_Chợ Nghĩa Phát": { di: "Tân Bình", ec: 6 },
"1. HCMC_Chợ Ông Hoàng": { di: "Tân Bình", ec: 13 },
"1. HCMC_Chợ Phạm Văn Hai": { di: "Tân Bình", ec: 24 },
"1. HCMC_Chợ Tạm Phạm Văn Bạch": { di: "Tân Bình", ec: 7 },
"1. HCMC_Chợ Tân Bình": { di: "Tân Bình", ec: 30 },
"1. HCMC_Chợ Tân Hưng": { di: "Tân Bình", ec: 5 },
"1. HCMC_Chợ Tân Phước": { di: "Tân Bình", ec: 8 },
"1. HCMC_Chợ Tân Trụ": { di: "Tân Bình", ec: 8 },
"1. HCMC_Chợ Trần Văn Quang": { di: "Tân Bình", ec: 6 },
"1. HCMC_Chợ Võ Thành Trang": { di: "Tân Bình", ec: 8 },
"1. HCMC_Chợ Hiệp Tân": { di: "Tân Phú", ec: 9 },
"1. HCMC_Chợ Hoàng Ngọc Phách": { di: "Tân Phú", ec: 8 },
"1. HCMC_Chợ Phú Trung": { di: "Tân Phú", ec: 8 },
"1. HCMC_Chợ Phường 17": { di: "Tân Phú", ec: 18 },
"1. HCMC_Chợ Phường 20": { di: "Tân Phú", ec: 15 },
"1. HCMC_Chợ Sơn Kỳ": { di: "Tân Phú", ec: 11 },
"1. HCMC_Chợ Tạm Huỳnh Văn Chính": { di: "Tân Phú", ec: 5 },
"1. HCMC_Chợ Tạm Thống Nhất": { di: "Tân Phú", ec: 5 },
"1. HCMC_Chợ Tân Hương": { di: "Tân Phú", ec: 5 },
"1. HCMC_Chợ Tân Phú 1": { di: "Tân Phú", ec: 6 },
"1. HCMC_Chợ An Bình": { di: "Thủ Đức", ec: 5 },
"1. HCMC_Chợ Bình Khánh": { di: "Thủ Đức", ec: 7 },
"1. HCMC_Chợ Bình Phước": { di: "Thủ Đức", ec: 8 },
"1. HCMC_Chợ Bình Triệu": { di: "Thủ Đức", ec: 6 },
"1. HCMC_Chợ Bình Trưng": { di: "Thủ Đức", ec: 5 },
"1. HCMC_Chợ Cát Lái": { di: "Thủ Đức", ec: 5 },
"1. HCMC_Chợ Cây Xoài": { di: "Thủ Đức", ec: 7 },
"1. HCMC_Chợ Đo Đạc": { di: "Thủ Đức", ec: 5 },
"1. HCMC_Chợ Hiệp Bình Chánh": { di: "Thủ Đức", ec: 10 },
"1. HCMC_Chợ Linh Trung": { di: "Thủ Đức", ec: 6 },
"1. HCMC_Chợ Linh Xuân": { di: "Thủ Đức", ec: 6 },
"1. HCMC_Chợ Tam Bình": { di: "Thủ Đức", ec: 9 },
"1. HCMC_Chợ Tam Hà": { di: "Thủ Đức", ec: 8 },
"1. HCMC_Chợ Tạm Hiệp Bình Chánh": { di: "Thủ Đức", ec: 5 },
"1. HCMC_Chợ Tân Lập": { di: "Thủ Đức", ec: 8 },
"1. HCMC_Chợ Thạnh Mỹ Lợi": { di: "Thủ Đức", ec: 5 },
"1. HCMC_Chợ Thảo Điền": { di: "Thủ Đức", ec: 5 },
"1. HCMC_Chợ Thủ Đức": { di: "Thủ Đức", ec: 12 },
"1. HCMC_Chợ Thủ Đức B": { di: "Thủ Đức", ec: 14 },
"1. HCMC_Chợ Từ Đức": { di: "Thủ Đức", ec: 6 },
"1. HCMC_Chợ Xuân Hiệp": { di: "Thủ Đức", ec: 5 },
"1. HCMC_Chợ Chó": { di: "Quận 12", ec: 5 },
"1. HCMC_Chợ Tăng Nhơn Phú": { di: "Thủ Đức", ec: 9 },
"1. HCMC_Chợ Việt Kiều": { di: "Hóc Môn", ec: 7 },
"1. HCMC_Chợ Tân Thới Thượng": { di: "Hóc Môn", ec: 7 },
"1. HCMC_Tạp Hóa": { di: "Chưa Rõ", ec: 1 },
"1. HCMC_Chợ 1A": { di: "Thủ Đức", ec: 5 },
"1. HCMC_Chợ Liên Ấp 123": { di: "Bình Chánh", ec: 5 },
"1. HCMC_Chợ Mỹ Nga": { di: "Bình Tân", ec: 7 },
"1. HCMC_Chợ Nhỏ": { di: "Quận 1", ec: 5 },
"1. HCMC_Chợ Nhỏ Hoàng Diệu": { di: "Quận 4", ec: 7 },
"1. HCMC_Chợ Hiệp Bình Phước": { di: "Thủ Đức", ec: 8 },

};